### PR TITLE
Groovy Rest example fails due to Unable to find loader for language=xml

### LINKED ISSUE #838: Groovy Rest example fails due to Unable to find loader for language=xml
**Step for reproduce:**
Runs example with
./kamel run --dev --name greetings --dependency camel-undertow --property camel.rest.port=8080 --open-api examples/greetings-api.json --logging-level org.apache.camel.k=DEBUG examples/greetings.groovy

**Output stack trace**
[1] Monitoring pod greetings-6cddfc4f7d-5g2hd[1] Starting the Java application using /opt/run-java/run-java.sh ...
[1] exec java -javaagent:/opt/jolokia/jolokia.jar=config=/opt/jolokia/etc/jolokia.properties -javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=9779:/opt/prometheus/prometheus-config.yml -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp ./resources:/etc/camel/conf:/etc/camel/resources:/etc/camel/sources/i-source-000:/etc/camel/sources/i-source-001:dependencies/com.github.ben-manes.caffeine.caffeine-2.7.0.jar:dependencies/com.google.errorprone.error_prone_annotations-2.3.3.jar:dependencies/commons-io.commons-io-2.6.jar:dependencies/io.undertow.undertow-core-1.4.26.Final.jar:dependencies/javax.servlet.javax.servlet-api-3.1.0.jar:dependencies/org.apache.camel.camel-api-3.0.0-M4.jar:dependencies/org.apache.camel.camel-base-3.0.0-M4.jar:dependencies/org.apache.camel.camel-caffeine-lrucache-3.0.0-M4.jar:dependencies/org.apache.camel.camel-cloud-3.0.0-M4.jar:dependencies/org.apache.camel.camel-core-3.0.0-M4.jar:dependencies/org.apache.camel.camel-core-engine-3.0.0-M4.jar:dependencies/org.apache.camel.camel-direct-3.0.0-M4.jar:dependencies/org.apache.camel.camel-groovy-3.0.0-M4.jar:dependencies/org.apache.camel.camel-http-common-3.0.0-M4.jar:dependencies/org.apache.camel.camel-jaxp-3.0.0-M4.jar:dependencies/org.apache.camel.camel-log-3.0.0-M4.jar:dependencies/org.apache.camel.camel-main-3.0.0-M4.jar:dependencies/org.apache.camel.camel-management-api-3.0.0-M4.jar:dependencies/org.apache.camel.camel-properties-3.0.0-M4.jar:dependencies/org.apache.camel.camel-support-3.0.0-M4.jar:dependencies/org.apache.camel.camel-undertow-3.0.0-M4.jar:dependencies/org.apache.camel.camel-util-3.0.0-M4.jar:dependencies/org.apache.camel.camel-util-json-3.0.0-M4.jar:dependencies/org.apache.camel.k.camel-k-loader-groovy-1.0.0-SNAPSHOT.jar:dependencies/org.apache.camel.k.camel-k-runtime-core-1.0.0-SNAPSHOT.jar:dependencies/org.apache.camel.k.camel-k-runtime-main-1.0.0-SNAPSHOT.jar:dependencies/org.apache.commons.commons-lang3-3.9.jar:dependencies/org.apache.logging.log4j.log4j-api-2.12.0.jar:dependencies/org.apache.logging.log4j.log4j-core-2.12.0.jar:dependencies/org.apache.logging.log4j.log4j-slf4j-impl-2.12.0.jar:dependencies/org.checkerframework.checker-qual-2.6.0.jar:dependencies/org.codehaus.groovy.groovy-2.5.7.jar:dependencies/org.jboss.logging.jboss-logging-3.3.2.Final.jar:dependencies/org.jboss.xnio.xnio-api-3.3.8.Final.jar:dependencies/org.jboss.xnio.xnio-nio-3.3.8.Final.jar:dependencies/org.slf4j.slf4j-api-1.7.26.jar org.apache.camel.k.main.Application
[1] OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
[1] I> No access restrictor found, access to any MBean is allowed
[1] Jolokia: Agent started with URL https://172.17.0.8:8778/jolokia/
[1] 2019-07-18 15:00:08.608 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.ContextConfigurer@3b35a229
[1] 2019-07-18 15:00:08.618 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesConfigurer@2235eaab
[1] 2019-07-18 15:00:08.619 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesDumper@3b6d844d
[1] 2019-07-18 15:00:08.670 INFO  [main] MainSupport - Using properties from classpath:application.properties
[1] 2019-07-18 15:00:08.951 INFO  [main] MainSupport - Auto-configuration summary:
[1] 2019-07-18 15:00:08.952 INFO  [main] MainSupport - 	camel.rest.port=8080
[1] 2019-07-18 15:00:08.963 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.ContextConfigurer@3b35a229 executed in phase ConfigureContext
[1] 2019-07-18 15:00:09.402 INFO  [main] RoutesConfigurer - Loading routes from: file:/etc/camel/sources/i-source-000/greetings.groovy?language=groovy
[1] 2019-07-18 15:00:10.371 INFO  [Camel Thread #0 - CamelHangupInterceptor] MainSupport$HangupInterceptor - Received hang up - stopping the main instance.
[1] Exception in thread "main" org.apache.camel.RuntimeCamelException: java.lang.IllegalArgumentException: Unable to find loader for: Source{location='file:/etc/camel/sources/i-source-001/greetings-api.xml', language=xml , compressed=false}
[1] 	at org.apache.camel.RuntimeCamelException.wrapRuntimeCamelException(RuntimeCamelException.java:52)
[1] 	at org.apache.camel.k.listener.RoutesConfigurer.load(RoutesConfigurer.java:68)
[1] 	at org.apache.camel.k.listener.RoutesConfigurer.accept(RoutesConfigurer.java:50)
[1] 	at org.apache.camel.k.listener.AbstractPhaseListener.accept(AbstractPhaseListener.java:32)
[1] 	at org.apache.camel.k.main.ApplicationRuntime$MainListenerAdapter.lambda$invokeListeners$0(ApplicationRuntime.java:142)
[1] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[1] 	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
[1] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[1] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[1] 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[1] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[1] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[1] 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[1] 	at org.apache.camel.k.main.ApplicationRuntime$MainListenerAdapter.invokeListeners(ApplicationRuntime.java:141)
[1] 	at org.apache.camel.k.main.ApplicationRuntime$MainListenerAdapter.configure(ApplicationRuntime.java:120)
[1] 	at org.apache.camel.main.MainSupport.postProcessCamelContext(MainSupport.java:785)
[1] 	at org.apache.camel.main.MainSupport.initCamelContext(MainSupport.java:646)
[1] 	at org.apache.camel.main.Main.doInit(Main.java:108)
[1] 	at org.apache.camel.support.service.ServiceSupport.init(ServiceSupport.java:61)
[1] 	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:88)
[1] 	at org.apache.camel.main.MainSupport.run(MainSupport.java:196)
[1] 	at org.apache.camel.k.main.ApplicationRuntime.run(ApplicationRuntime.java:65)
[1] 	at org.apache.camel.k.main.Application.main(Application.java:44)
[1] Caused by: java.lang.IllegalArgumentException: Unable to find loader for: Source{location='file:/etc/camel/sources/i-source-001/greetings-api.xml', language=xml , compressed=false}
[1] 	at org.apache.camel.k.support.RuntimeSupport.lookupLoaderFromResource(RuntimeSupport.java:169)
[1] 	at org.apache.camel.k.support.RuntimeSupport.lambda$loaderFor$7(RuntimeSupport.java:158)
[1] 	at java.util.Optional.orElseGet(Optional.java:267)
[1] 	at org.apache.camel.k.support.RuntimeSupport.loaderFor(RuntimeSupport.java:158)
[1] 	at org.apache.camel.k.listener.RoutesConfigurer.load(RoutesConfigurer.java:65)
[1] 	... 21 more
[1] Caused by: org.apache.camel.NoFactoryAvailableException: Cannot find factory class for resource: xml
[1] 	at org.apache.camel.impl.engine.DefaultFactoryFinder.newInstance(DefaultFactoryFinder.java:61)
[1] 	at org.apache.camel.k.support.RuntimeSupport.lookupLoaderFromResource(RuntimeSupport.java:167)
[1] 	... 25 more
[1] Caused by: org.apache.camel.NoFactoryAvailableException: Cannot find factory class for resource: META-INF/services/org/apache/camel/k/loader/xml
[1] 	at org.apache.camel.impl.engine.DefaultFactoryFinder.doFindFactoryProperties(DefaultFactoryFinder.java:145)
[1] 	at org.apache.camel.impl.engine.DefaultFactoryFinder.access$000(DefaultFactoryFinder.java:40)
[1] 	at org.apache.camel.impl.engine.DefaultFactoryFinder$1.get(DefaultFactoryFinder.java:86)
[1] 	at org.apache.camel.impl.engine.DefaultFactoryFinder$2.apply(DefaultFactoryFinder.java:172)
[1] 	at org.apache.camel.impl.engine.DefaultFactoryFinder$2.apply(DefaultFactoryFinder.java:168)
[1] 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
[1] 	at org.apache.camel.impl.engine.DefaultFactoryFinder.addToClassMap(DefaultFactoryFinder.java:168)
[1] 	at org.apache.camel.impl.engine.DefaultFactoryFinder.findClass(DefaultFactoryFinder.java:83)
[1] 	at org.apache.camel.impl.engine.DefaultFactoryFinder.newInstance(DefaultFactoryFinder.java:98)
[1] 	at org.apache.camel.impl.engine.DefaultFactoryFinder.newInstance(DefaultFactoryFinder.java:59)
[1] 	... 26 more
[1] 2019-07-18 15:00:10.553 INFO  [Camel Thread #0 - CamelHangupInterceptor] DefaultCamelContext - Apache Camel 3.0.0-M4 (CamelContext: camel-k) is shutting down
[1] 2019-07-18 15:00:10.559 INFO  [Camel Thread #0 - CamelHangupInterceptor] MainLifecycleStrategy - CamelContext: camel-k has been shutdown, triggering shutdown of the JVM.
[1] 2019-07-18 15:00:10.566 INFO  [Camel Thread #0 - CamelHangupInterceptor] DefaultCamelContext - Apache Camel 3.0.0-M4 (CamelContext: camel-k) uptime 
[1] 2019-07-18 15:00:10.570 INFO  [Camel Thread #0 - CamelHangupInterceptor] DefaultCamelContext - Apache Camel 3.0.0-M4 (CamelContext: camel-k) is shutdown in 0.195 seconds

**Looks like, will need explicitly add camel-k-loader-xml when using openAPI. If yes, I will fix this issue.**

### PR DESCRIPTION
**Pull request by dmvolod**
Fixes #838

### CODE REVIEW

File: pkg/trait/dependencies.go [hunk 1]
```diff
@@ -50,7 +50,7 @@ func (t *dependenciesTrait) Apply(e *Environment) error {
 			util.StringSliceUniqueAdd(&dependencies, dep)
 		}
 	}
-	for _, s := range e.Integration.Spec.Sources {
+	for _, s := range append(e.Integration.Spec.Sources, e.Integration.Status.GeneratedSources...) {
```
Comment (lburgazzoli) [inline pkg/trait/dependencies.go]: Not sure about this as it could eventually append GeneratedSources to Sources if the underlying slice has some capacity.

There is an utility method `Integration.Sources()` that should properly combine the two sources

Comment (dmvolod) [reply pkg/trait/dependencies.go]: Thanks @lburgazzoli , fixed.

Comment (lburgazzoli) [reply pkg/trait/dependencies.go]: there is a lint issue

    pkg/trait/dependencies_test.go:171: line is 178 characters

**Comment by dmvolod** [comment]
I can see this in Travis, but on my laptop 'make lint' command hangs. I will check and fix it asap.

**Comment by lburgazzoli** [comment]
You may need to tweak  the lint parameters otherwise the linter will eat up all your memory and cpu, i.e. in travis it runs with:

```
GOGC=10 ./golangci-lint run --verbose --deadline 5m --config .golangci.yml
```

**Comment by dmvolod** [comment]
Thanks, @lburgazzoli, fixed.
I would like to create add fix your provided to the 'make lint' command invoke.
