### PR TITLE
Automatically resolve dependencies for language expressions

### LINKED ISSUE #914: Automatically resolve dependecy for language expressions (eg: groovy)
Camel-K can't automatically resolve camel-groovy dependency when using groovy expression inside camel route. See the following route using a groovy expression that try to extract a substring from the exchange body:

```java
import org.apache.camel.builder.RouteBuilder;

public class Sample extends RouteBuilder {
  @Override
  public void configure() throws Exception {
    from("timer:tick")
      .setBody(simple("Rafael Torres Coelho Soares"))
      .setHeader("h1").groovy("request.body.substring(7)")
      .log("Hello ${body} [headers h1: ${headers.h1}]");
  }
}
```

If you run with no explicit dependency:

```
> kamel run --dev Sample.java
```

You will get the followinf error:
```
[2] Exception in thread "main" org.apache.camel.FailedToCreateRouteException: Failed to create route route1 at: >>> SetHeader[h1, groovy{request.body.substring(7)}] <<< in route: Route(route1)[From[timer:tick] -> [SetBody[Simple: Rafael To... because of No language could be found for: groovy
[2] 	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:357)
```

But if you explicitly specify `camel-groovy` dep it works

```
kamel run --dev -d camel-groovy examples/Sample.java
```
0.280 seconds
[1] 2019-08-22 12:28:33.411 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.RoutesDumper@415b0b49 executed in phase Started
[1] 2019-08-22 12:28:35.231 INFO  [Camel (camel-k) thread #2 - timer://tick] route1 - Hello Rafael Torres Coelho Soares [headers h1: Torres Coelho Soares]
[1] 2019-08-22 12:28:35.409 INFO  [Camel (camel-k) thread #2 - timer://tick] route1 - Hello Rafael Torres Coelho Soares [headers h1: Torres Coelho Soares]
[1] 2019-08-22 12:28:36.409 INFO  [Camel (camel-k) thread #2 - timer://tick] route1 - Hello Rafael Torres Coelho Soares [headers h1: Torres Coelho Soares]
[1] 2019-08-22 12:28:37.409 INFO  [Camel (camel-k) thread #2 - timer://tick] route1 - Hello Rafael Torres Coelho Soares [headers h1: Torres Coelho Soares]
[1] 2019-08-22 12:28:38.410 INFO  [Camel (camel-k) thread #2 - timer://tick] route1 - Hello Rafael Torres Coelho Soares [headers h1: Torres Coelho Soares]
```

```

### LINKED ISSUE #929: routes.yaml example fails with NoSuchLanguageException
The body uppercase transformation in the [routes.yaml](https://github.com/apache/camel-k/blob/master/examples/routes.yaml#L10) example results in:

```
2019-09-10 08:50:02.245 WARN  [Camel (camel-k) thread #2 - timer://tick] TimerConsumer - Error processing exchange. Exchange[ID-routes-6559d6b457-vlsxl-1568105397257-0-3]. Caused by: [org.apache.camel.NoSuchLanguageException - No language could be found for: bean]
org.apache.camel.NoSuchLanguageException: No language could be found for: bean
	at org.apache.camel.impl.engine.DefaultLanguageResolver.noSpecificLanguageFound(DefaultLanguageResolver.java:91) ~[org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.impl.engine.DefaultLanguageResolver.resolveLanguage(DefaultLanguageResolver.java:67) ~[org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.impl.engine.AbstractCamelContext.resolveLanguage(AbstractCamelContext.java:1619) ~[org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.support.builder.ExpressionBuilder$68.evaluate(ExpressionBuilder.java:1527) ~[org.apache.camel.camel-support-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.support.ExpressionAdapter.evaluate(ExpressionAdapter.java:34) ~[org.apache.camel.camel-support-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.language.simple.SimpleExpressionBuilder$29.evaluate(SimpleExpressionBuilder.java:668) ~[org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.support.ExpressionAdapter.evaluate(ExpressionAdapter.java:34) ~[org.apache.camel.camel-support-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.builder.SimpleBuilder.evaluate(SimpleBuilder.java:99) ~[org.apache.camel.camel-core-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.processor.SetBodyProcessor.process(SetBodyProcessor.java:43) ~[org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryState.run(RedeliveryErrorHandler.java:480) ~[org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:185) [org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59) [org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:87) [org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:222) [org.apache.camel.camel-base-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:193) [org.apache.camel.camel-timer-3.0.0-M4.jar:3.0.0-M4]
	at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:75) [org.apache.camel.camel-timer-3.0.0-M4.jar:3.0.0-M4]
	at java.util.TimerThread.mainLoop(Timer.java:555) [?:1.8.0_191]
	at java.util.TimerThread.run(Timer.java:505) [?:1.8.0_191]

```

If you manually add a dependency for `camel-bean` it works fine. Not sure if that's the intended way to make the example work, but it'd be nice if it worked OOTB.

### PR DESCRIPTION
**Pull request by jamesnetherton**
fixes #914
fixes #929

### CODE REVIEW

File: pkg/util/source/inspector.go [hunk 1]
```diff
@@ -35,13 +35,22 @@ var (
...
+		`.*restConfiguration().*`:                         "camel:rest",
+		`.*rest(("[a-zA-Z0-9-/]+")*).*`:                   "camel:rest",
+		`^\s*rest\s*{.*`:                                  "camel:rest",
+		`.*\.groovy\s*\(.*\).*`:                           "camel:groovy",
+		`.*\.(jsonpath|jsonpathWriteAsString)\s*\(.*\).*`: "camel:jsonpath",
+		`.*\.ognl\s*\(.*\).*`:                             "camel:ognl",
+		`.*\.mvel\s*\(.*\).*`:                             "camel:mvel",
+		`.*\.?simple\s*\(.*\).*`:                          "camel:bean",
+		`.*\.xquery\s*\(.*\).*`:                           "camel:saxon",
+		`.*\.xpath\s*\(.*\).*`:                            "camel:xpath",
```
Comment (lburgazzoli) [inline pkg/util/source/inspector.go]: I think `xpath` exists also in a form of `transform(xpath(...))`

Comment (jamesnetherton) [reply pkg/util/source/inspector.go]: Thanks, I pushed a fix + test for that.
