### PR TITLE
bugfix(#5755): avoiding deadlock between builds with dependencies build order strategy

### LINKED ISSUE #5755: Possible deadlock between integration builds
### What happened?

After creating 4 integrations at the same time, 3 of the builds are hanging for minutes after the first build has finished.

### Steps to reproduce

- Clean up all Integration Kits on the Camel K installation.
- Create the following Integrations using a single yaml file:
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: deploy-a41357e7-14c0-4a64-9933-80044f023ad3-381
spec:  
  sources:
  - name: main.yaml
    content: |-
      - from:
          uri: quartz://ipaas/trigger?cron=0+*+*+?+*+*
          steps:
          - log:
              message: "It worked"
  traits:
    camel:
      runtimeVersion: 3.8.1
    cron:
      fallback: true
---
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: deploy-a41357e7-14c0-4a64-9933-80044f023ad3-323
spec:  
  sources:
  - name: main.yaml
    content: |-
      - from:
          uri: quartz://ipaas/trigger?cron=0+*+*+?+*+*
          steps:
          - log:
              message: "It worked"
  traits:
    camel:
      runtimeVersion: 3.2.3
    cron:
      fallback: true
---
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: deploy-fc949ea7-e5ea-4d59-8fed-83471b9350e0-381
spec:  
  sources:
  - name: main.yaml
    content: |-
      - from:
          uri: rest:get:/demo
          steps:
          - setBody:
              constant: "It worked"
  traits:
    knative-service:
      minScale: 1
    camel:
      runtimeVersion: 3.8.1
---
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: deploy-fc949ea7-e5ea-4d59-8fed-83471b9350e0-323
spec:  
  sources:
  - name: main.yaml
    content: |-
      - from:
          uri: rest:get:/demo
          steps:
          - setBody:
              constant: "It worked"
  traits:
    knative-service:
      minScale: 1
    camel:
      runtimeVersion: 3.2.3
```

This will create 4 Builds:
```
NAME                       PHASE        AGE   STARTED   DURATION   ATTEMPTS
kit-cqqft44lsn2s73ed6ufg   Running      55s   55s                  
kit-cqqft44lsn2s73ed6ug0   Scheduling   55s                        
kit-cqqft4clsn2s73ed6ugg   Scheduling   54s                        
kit-cqqft4clsn2s73ed6uh0   Scheduling   54s                        
```
- Wait for the first build to finish.
- Keep waiting for the second build to start.
- Even after minutes waiting, the build is still in Scheduling status; (I waited for ~5 minutes)

Checking the operator log I see:

```
{"level":"info","ts":"2024-08-08T17:24:23Z","logger":"camel-k.controller.build","msg":"Waiting for build (kit-cqqft44lsn2s73ed6ug0) to finish in order to use incremental image builds - the build (kit-cqqft4clsn2s73ed6uh0) gets enqueued","request-namespace":"a1b2c3d4e5","request-name":"deploy-fc949ea7-e5ea-4d59-8fed-83471b9350e0-323","order-strategy":"dependencies","api-version":"camel.apache.org/v1","kind":"Build","ns":"a1b2c3d4e5","name":"kit-cqqft4clsn2s73ed6uh0"}
{"level":"info","ts":"2024-08-08T17:24:27Z","logger":"camel-k.controller.build","msg":"Waiting for build (kit-cqqft4clsn2s73ed6ugg) to finish in order to use incremental image builds - the build (kit-cqqft44lsn2s73ed6ug0) gets enqueued","request-namespace":"a1b2c3d4e5","request-name":"deploy-a41357e7-14c0-4a64-9933-80044f023ad3-323","order-strategy":"dependencies","api-version":"camel.apache.org/v1","kind":"Build","ns":"a1b2c3d4e5","name":"kit-cqqft44lsn2s73ed6ug0"}
{"level":"info","ts":"2024-08-08T17:24:27Z","logger":"camel-k.controller.build","msg":"Waiting for build (kit-cqqft44lsn2s73ed6ug0) to finish in order to use incremental image builds - the build (kit-cqqft4clsn2s73ed6ugg) gets enqueued","request-namespace":"a1b2c3d4e5","request-name":"deploy-fc949ea7-e5ea-4d59-8fed-83471b9350e0-381","order-strategy":"dependencies","api-version":"camel.apache.org/v1","kind":"Build","ns":"a1b2c3d4e5","name":"kit-cqqft4clsn2s73ed6ugg"}
{"level":"info","ts":"2024-08-08T17:24:28Z","logger":"camel-k.controller.build","msg":"Waiting for build (kit-cqqft44lsn2s73ed6ug0) to finish in order to use incremental image builds - the build (kit-cqqft4clsn2s73ed6uh0) gets enqueued","request-namespace":"a1b2c3d4e5","request-name":"deploy-fc949ea7-e5ea-4d59-8fed-83471b9350e0-323","order-strategy":"dependencies","api-version":"camel.apache.org/v1","kind":"Build","ns":"a1b2c3d4e5","name":"kit-cqqft4clsn2s73ed6uh0"}
{"level":"info","ts":"2024-08-08T17:24:32Z","logger":"camel-k.controller.build","msg":"Waiting for build (kit-cqqft4clsn2s73ed6ugg) to finish in order to use incremental image builds - the build (kit-cqqft44lsn2s73ed6ug0) gets enqueued","request-namespace":"a1b2c3d4e5","request-name":"deploy-a41357e7-14c0-4a64-9933-80044f023ad3-323","order-strategy":"dependencies","api-version":"camel.apache.org/v1","kind":"Build","ns":"a1b2c3d4e5","name":"kit-cqqft44lsn2s73ed6ug0"}
{"level":"info","ts":"2024-08-08T17:24:32Z","logger":"camel-k.controller.build","msg":"Waiting for build (kit-cqqft44lsn2s73ed6ug0) to finish in order to use incremental image builds - the build (kit-cqqft4clsn2s73ed6ugg) gets enqueued","request-namespace":"a1b2c3d4e5","request-name":"deploy-fc949ea7-e5ea-4d59-8fed-83471b9350e0-381","order-strategy":"dependencies","api-version":"camel.apache.org/v1","kind":"Build","ns":"a1b2c3d4e5","name":"kit-cqqft4clsn2s73ed6ugg"}
{"level":"info","ts":"2024-08-08T17:24:33Z","logger":"camel-k.controller.build","msg":"Waiting for build (kit-cqqft44lsn2s73ed6ug0) to finish in order to use incremental image builds - the build (kit-cqqft4clsn2s73ed6uh0) gets enqueued","request-namespace":"a1b2c3d4e5","request-name":"deploy-fc949ea7-e5ea-4d59-8fed-83471b9350e0-323","order-strategy":"dependencies","api-version":"camel.apache.org/v1","kind":"Build","ns":"a1b2c3d4e5","name":"kit-cqqft4clsn2s73ed6uh0"}
{"level":"info","ts":"2024-08-08T17:24:37Z","logger":"camel-k.controller.build","msg":"Waiting for build (kit-cqqft4clsn2s73ed6ugg) to finish in order to use incremental image builds - the build (kit-cqqft44lsn2s73ed6ug0) gets enqueued","request-namespace":"a1b2c3d4e5","request-name":"deploy-a41357e7-14c0-4a64-9933-80044f023ad3-323","order-strategy":"dependencies","api-version":"camel.apache.org/v1","kind":"Build","ns":"a1b2c3d4e5","name":"kit-cqqft44lsn2s73ed6ug0"}
{"level":"info","ts":"2024-08-08T17:24:37Z","logger":"camel-k.controller.build","msg":"Waiting for build (kit-cqqft44lsn2s73ed6ug0) to finish in order to use incremental image builds - the build (kit-cqqft4clsn2s73ed6ugg) gets enqueued","request-namespace":"a1b2c3d4e5","request-name":"deploy-fc949ea7-e5ea-4d59-8fed-83471b9350e0-381","order-strategy":"dependencies","api-version":"camel.apache.org/v1","kind":"Build","ns":"a1b2c3d4e5","name":"kit-cqqft4clsn2s73ed6ugg"}
{"level":"info","ts":"2024-08-08T17:24:38Z","logger":"camel-k.controller.build","msg":"Waiting for build (kit-cqqft44lsn2s73ed6ug0) to finish in order to use incremental image builds - the build (kit-cqqft4clsn2s73ed6uh0) gets enqueued","request-namespace":"a1b2c3d4e5","request-name":"deploy-fc949ea7-e5ea-4d59-8fed-83471b9350e0-323","order-strategy":"dependencies","api-version":"camel.apache.org/v1","kind":"Build","ns":"a1b2c3d4e5","name":"kit-cqqft4clsn2s73ed6uh0"}
```
It seems like each build is waiting for another one to finish;

 

### Relevant log output

_No response_

### Camel K version

2.4.0

### PR DESCRIPTION
**Pull request by lsergio**
Closes #5755 

**Release Note**
```release-note
Fixed dependencies build order strategy to avoid deadlocks
```

### CODE REVIEW

File: pkg/apis/camel/v1/build_types_support.go [hunk 1]
```diff
@@ -311,10 +332,27 @@ func (bl BuildList) HasMatchingBuild(build *Build) (bool, *Build) {
 				// additionally check for the creation timestamp
 				if b.CreationTimestamp.Before(&build.CreationTimestamp) {
 					return true, &b
+				} else if b.CreationTimestamp.Equal(&build.CreationTimestamp) {
```
Comment (squakez) [inline pkg/apis/camel/v1/build_types_support.go:335]: I think this extra condition check is okey.

**Review by squakez — COMMENTED** [review]
Thanks for the PR. I think the extra condition check you've added when the time is exactly equal should be enough to avoid the deadlock. I am not sure to understand why you're changing the rest of the algorithm. Also +1 on the unit tests.

File: pkg/apis/camel/v1/build_types_support.go (hunk 1 above)
Comment (lsergio) [reply pkg/apis/camel/v1/build_types_support.go:335]: This condition is included in the block that handles the cases where all dependencies are matching. 
However, while testing, I saw the issue happening where at least half, but not all of the dependencies match. Each build kept waiting for the other one.
This is the scenario in the test case `TestMatchingBuildsSchedulingSharedDependencies`.
I handle it in the first `else` block.
Before it would just return true, causing the deadlock:
```
			} else if missing > 0 {
				// found another suitable scheduled build with fewer dependencies that should build first in order to reuse the produced image
				return true, &b
```
I also included a runtime check. If the builds have different runtime versions, they can't share images and thus there's no reason to wait.

**Comment by squakez** [comment]
> LGTM. Just a small question : wouldn't it be better to use `defaults.DefaultRuntimeVersion` instead of "3.8.1" in the tests ?

Yeah, @lsergio it would be good if you can change in order to maintain consistency with the default settings (and other tests using the same). Thanks!

**Comment by lsergio** [comment]
> > LGTM. Just a small question : wouldn't it be better to use `defaults.DefaultRuntimeVersion` instead of "3.8.1" in the tests ?
> 
> Yeah, @lsergio it would be good if you can change in order to maintain consistency with the default settings (and other tests using the same). Thanks!

Hi @squakez and @gansheer. When I do it, I get the following error while building:

```
# github.com/apache/camel-k/v2/pkg/apis/camel/v1
package github.com/apache/camel-k/v2/pkg/apis/camel/v1
	imports github.com/apache/camel-k/v2/pkg/util/defaults
	imports github.com/apache/camel-k/v2/pkg/util/log
	imports github.com/apache/camel-k/v2/pkg/apis/camel/v1: import cycle not allowed in test
```
It is not really clear for me why this is happening. :( 
If someone can provide some hint, that would be greate. I googled for the error and could not find anything helpful.
For the test purpose, though, the runtime versions could be anything. I could have called them "runtime-1" and "runtime-2", for example.

**Comment by squakez** [comment]
It's a circular reference loop. Yeah, let's keep this way then. Merging, thanks!
