### PR TITLE
fix(cli): Remove CamelCatalogs CR on kamel uninstall

### LINKED ISSUE #4160: Kamel cli reset/uninstall --all does not clean the camelcatalog
Using the client kamel to remove the operator with the commands `kamel reset` then `kamel uninstall --all` does not remove the camel catalog CR.
It contains a status referencing the builder container availability:
```yaml
status:
  conditions:
  - lastTransitionTime: "2023-03-24T08:17:03Z"
    lastUpdateTime: "2023-03-24T08:17:03Z"
    message: Container image successfully built
    reason: Builder Image
    status: "True"
    type: Ready
  image: 10.109.132.152/default/camel-k-runtime-quarkus-builder:3.20.1-snapshot
  observedGeneration: 1
  phase: Ready
```

When installing new code with `kamel install` on the same kubernetes cluster, the camel catalog CR still exists. The effect is that the builder container is not rebuild by the camel-k operator.

I suggest we remove the camel catalog in the `kamel uninstall --all`. Anything that is against that modification in the new builder design @squakez ?

### PR DESCRIPTION
**Pull request by gansheer**
Fixes #4160 

## Motivation

When using `kamel uninstall` command the CamelCatalogs CR are not removed from the cluster. When an operator with the same Runtime is installed, it is already considered as Ready so the builder image container is not builded again with the code from the operator.

## Description

Remove all the CamelCatalogs in the namespace of the operator on `kamel uninstall call` and add a `skip-camel-catalogs` flag.

**Release Note**
```release-note
Fix(cli): Remove CamelCatalogs CR on kamel uninstall
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by squakez — APPROVED** [review]

File: pkg/util/defaults/defaults.go [hunk 1]
```diff
@@ -26,7 +26,7 @@ const (
 	Version = "2.0.0-SNAPSHOT"
 
 	// DefaultRuntimeVersion --
-	DefaultRuntimeVersion = "1.18.0-SNAPSHOT"
+	DefaultRuntimeVersion = "3.20.1-SNAPSHOT"
```
Comment (gansheer) [inline pkg/util/defaults/defaults.go:29]: This was changed automatically, should I revert this change ?

Comment (squakez) [reply pkg/util/defaults/defaults.go:29]: No, it's okey to keep it.

**Comment by squakez** [comment]
Please, let me know when this is ready to be merged.

**Comment by squakez** [comment]
Check failure unrelated. Merging.

**Comment by gansheer** [comment]
Thanks.
