### PR TITLE
fix(kamel log): Use integration name for looking up containers

### LINKED ISSUE #347: Use container name for "kamel log", too
When running "kamel log" on an istio enabled cluster the following output is generated:

```
./kamel log sample
WARN[0000] error caught during log scraping for pod sample-c5f9598b5-7fh6m: a container name must be specified for pod sample-c5f9598b5-7fh6m, choose one of: [sample istio-proxy] or one of the init containers: [istio-init]
WARN[0005] error caught during log scraping for pod sample-c5f9598b5-7fh6m: a container name must be specified for pod sample-c5f9598b5-7fh6m, choose one of: [sample istio-proxy] or one of the init containers: [istio-init]
```

As `kamel log` also knows the name of the container (i.e. its the same as the integration), it could specify that implicitly when calling out to the logging API.

### PR DESCRIPTION
**Pull request by rhuss**
Use integration name for looking up containers as a fallback if no
container could be found.

If no container could be identified even with the integration name,
use the first container for the log, assuming its the "main" container.

Fixes #347

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@rhuss seems ok, did you test against knative ?

File: pkg/util/log/annotation_scraper.go [hunk 1]
```diff
@@ -36,16 +36,18 @@ import (
...
 	namespace     string
+	integrationName string
 	labelSelector string
 	podScrapers   sync.Map
 	counter       uint64
 }
 
 // NewSelectorScraper creates a new SelectorScraper
-func NewSelectorScraper(client kubernetes.Interface, namespace string, labelSelector string) *SelectorScraper {
+func NewSelectorScraper(client kubernetes.Interface, namespace string, integrationName string, labelSelector string) *SelectorScraper {
```
Comment (lburgazzoli) [inline pkg/util/log/annotation_scraper.go]: if possible I would not use the name integration in this package

**Comment by rhuss** [comment]
Yes, I have knative installed locally in minikube.

File: pkg/util/log/annotation_scraper.go (hunk 1 above)
Comment (rhuss) [reply pkg/util/log/annotation_scraper.go]: Ok, what's about `defaultContainerName` ?

**Comment by rhuss** [comment]
Le me fix the build issue.

File: pkg/util/log/annotation_scraper.go (hunk 1 above)
Comment (lburgazzoli) [reply pkg/util/log/annotation_scraper.go]: fine with me

**Comment by rhuss** [comment]
@lburgazzoli not sure about the build error. Seems to be unrelated to this PR ?

**Comment by lburgazzoli** [comment]
looks like you need to rebase from master
