### PR TITLE
fix(ci): remove unused maven references

### LINKED ISSUE #2659: Remove maven wrapper and any leftover pom.xml

### PR DESCRIPTION
**Pull request by squakez**
Remove any `.mvnw` and any other pom we used to maintain.

- [x] Remove `.mvnw` references
- [x] Change the way we `make images-dev` to remove the pom.xml dependency

Closes #2659

**Release Note**
```release-note
fix(ci): remove unused maven references
```

### CODE REVIEW

File: script/get_catalog.sh [hunk 1]
```diff
@@ -21,14 +21,12 @@ rootdir=$location/../
...
-  $rootdir/mvnw -q \
-    -f ${rootdir}/build/maven/pom-catalog.xml \
-    -Dcatalog.path=${rootdir}/resources \
-    -Druntime.version=$runtimeVersion \
-    -B \
-    -U \
-    "$@"
+  # the catalog was already provided by Camel K runtime. No need to depends on maven to rebuild it
+  wget -q https://repo1.maven.org/maven2/org/apache/camel/k/camel-k-catalog/$runtimeVersion/camel-k-catalog-$runtimeVersion-catalog.yaml -O ${rootdir}/resources/camel-catalog-$runtimeVersion.yaml
+  # TODO if we need to use also staging, then we must parse the maven-metadata from the staging repository
```
Comment (squakez) [inline script/get_catalog.sh:26]: @oscerd I'd like your opinion here. When we're using stable version, we should be fine picking up the catalog built. Is there any interim situation where we're using `SNAPSHOT` (ie, during release process)? if so, I can work to include it as described in the TODO comment.

Comment (squakez) [reply script/get_catalog.sh:26]: Thanks. Then, I'll proceed with the other points in the PR and if all is fine I will merge. If it happens anything wrong during the release process I'll handle.

**Review by tadayosi — APPROVED** [review]
