### PR TITLE
Fix #2530: fix type and do not add cross-namespace owner references

### LINKED ISSUE #2530: Error in OpenShift image-pull delegation on IBM Cloud
The operator fails to create the RoleBinding that binds the `system:image-puller` `ClusterRole` to the integration service account (pull-secret trait).

This happens when the operator is installed globally and no `IntegrationPlatform` is created in the user namespace.

The final result is that the pod can't start (image pull error).

Operator logs:
```
{"level":"error","ts":1627317698.8724444,"logger":"controller-runtime.manager.controller.integration-controller","msg":"Reconciler error","name":"example","namespace":"nf-test","error":"error executing post actions: error during apply resource: &RoleBinding{ObjectMeta:{camel-k-puller-nf-test  openshift-operators    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[camel.apache.org/generation:1 camel.apache.org/integration:example] map[] [{camel.apache.org/v1 Integration example 8abd7803-d2b4-429a-89d6-4f1ffcba30c9 0xc0017d0141 0xc0017d0142}] []  []},Subjects:[]Subject{Subject{Kind:ServiceAccount,APIGroup:,Name:default,Namespace:nf-test,},},RoleRef:RoleRef{APIGroup:,Kind:ClusterRole,Name:system:image-puller,},}: Object 'Kind' is missing in 'unstructured object has no kind'","errorVerbose":"Object 'Kind' is missing in 'unstructured object has no kind'\nerror during apply resource: &RoleBinding{ObjectMeta:{camel-k-puller-nf-test  openshift-operators    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[camel.apache.org/generation:1 camel.apache.org/integration:example] map[] [{camel.apache.org/v1 Integration example 8abd7803-d2b4-429a-89d6-4f1ffcba30c9 0xc0017d0141 0xc0017d0142}] []  []},Subjects:[]Subject{Subject{Kind:ServiceAccount,APIGroup:,Name:default,Namespace:nf-test,},},RoleRef:RoleRef{APIGroup:,Kind:ClusterRole,Name:system:image-puller,},}\ngithub.com/apache/camel-k/pkg/trait.(*deployerTrait).serverSideApply\n\tgithub.com/apache/camel-k/pkg/trait/deployer.go:123\ngithub.com/apache/camel-k/pkg/trait.(*deployerTrait).Apply.func2\n\tgithub.com/apache/camel-k/pkg/trait/deployer.go:95\ngithub.com/apache/camel-k/pkg/trait.Apply\n\tgithub.com/apache/camel-k/pkg/trait/trait.go:52\ngithub.com/apache/camel-k/pkg/controller/integration.(*deployAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/integration/deploy.go:56\ngithub.com/apache/camel-k/pkg/controller/integration.(*reconcileIntegration).Reconcile\n\tgithub.com/apache/camel-k/pkg/controller/integration/integration_controller.go:324\ngithub.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile\n\tgithub.com/apache/camel-k/pkg/util/monitoring/controller.go:71\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99\nruntime.goexit\n\truntime/asm_amd64.s:1374\nerror executing post actions\ngithub.com/apache/camel-k/pkg/trait.Apply\n\tgithub.com/apache/camel-k/pkg/trait/trait.go:54\ngithub.com/apache/camel-k/pkg/controller/integration.(*deployAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/integration/deploy.go:56\ngithub.com/apache/camel-k/pkg/controller/integration.(*reconcileIntegration).Reconcile\n\tgithub.com/apache/camel-k/pkg/controller/integration/integration_controller.go:324\ngithub.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile\n\tgithub.com/apache/camel-k/pkg/util/monitoring/controller.go:71\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99\nruntime.goexit\n\truntime/asm_amd64.s:1374","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\tsigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\tk8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99"}
```

### PR DESCRIPTION
**Pull request by nicolaferraro**
**Release Note**
```release-note
Fixed ImagePullError when using global operator in OpenShift
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: pkg/trait/pull_secret.go [hunk 1]
```diff
@@ -122,6 +122,10 @@ func (t *pullSecretTrait) newImagePullerRoleBinding(e *Environment) *rbacv1.Role
 		serviceAccount = "default"
 	}
 	return &rbacv1.RoleBinding{
```
Comment (astefanutti) [inline pkg/trait/pull_secret.go:124]: I wonder if there would be a logical owner reference for that resource, so that it gets garbage collected when no needed anymore. Maybe the IntegrationPlatform could be the owner?

Also I think there is an issue when two Integrations in the same namespace use different service accounts, as the RoleBinding will be updated with the last one. I wonder if a single RoleBinding maintaining all the subjects for the global platform could work, but that'd probably be more involved to implement.

File: pkg/trait/owner.go [hunk 2]
```diff
@@ -78,17 +78,20 @@ func (t *ownerTrait) Apply(e *Environment) error {
...
-		references := []metav1.OwnerReference{
-			{
-				APIVersion:         e.Integration.APIVersion,
-				Kind:               e.Integration.Kind,
-				Name:               e.Integration.Name,
-				UID:                e.Integration.UID,
-				Controller:         &controller,
-				BlockOwnerDeletion: &blockOwnerDeletion,
-			},
+		// Avoid setting owner references across namespaces (resources are asynchronously refused by the api server)
```
Comment (astefanutti) [inline pkg/trait/owner.go:81]: I think we can even say that cross-namespace owner references are forbidden.

File: pkg/trait/pull_secret.go (hunk 1 above)
Comment (nicolaferraro) [reply pkg/trait/pull_secret.go:124]: Right, previously the resource was created directly by the trait, but a [recent change](https://github.com/apache/camel-k/commit/17cf52fc72a518fe44506ae97514a32ed444ce1c#diff-ffe17df62455fe57d1838af003526f25a73d77e84e950fdb275ea162e7699d96L114-L131) made it pass from the trait cycle, so it got updated in the owner trait.

I think it's ok to attach them to the integrationplatform, +1.

The problem with multiple sas is real.. To simplify things, we can use a different naming convention, attaching the name of the service account to the rolebinding's name (rather than managing multiple subjects), so that we can have multiple ones without issues.

File: pkg/trait/owner.go (hunk 2 above)
Comment (nicolaferraro) [reply pkg/trait/owner.go:81]: Yes, I put that description because the problem is a bit more subtle than that. I don't know if it's a consequence of the server-side apply, but if you use an invalid owner, you don't get absolutely any error in the operator. The error comes later and it is only visible in the Kubernetes cluster events. If you don't watch them, you just don't find the resource that the operator thinks he has created... 

Is this expected @astefanutti ?

File: pkg/trait/pull_secret.go (hunk 1 above)
Comment (astefanutti) [reply pkg/trait/pull_secret.go:124]: Ah looking at the offending commit, I wonder whether it might been better to revert back to having the trait managing the resource directly instead of adding it the environment resources. It's not a typical resource, and it seems safer to manage it directly to avoid any new side effect in the future.

File: pkg/trait/owner.go (hunk 2 above)
Comment (astefanutti) [reply pkg/trait/owner.go:81]: hum that's a very good question :) I've never noticed it, probably because of the behaviour you describe. It seems there have been some issue with invalid references, like kubernetes/kubernetes#65200. I would not expect it to have something to do with server-side apply, but more an issue with how invalid references are handled asynchronously.

Comment (nicolaferraro) [reply pkg/trait/owner.go:81]: Ok, if it's only limited to these cases of invalid references it's not a great issue after we deal with them..

Comment (astefanutti) [reply pkg/trait/owner.go:81]: Yes I agree. The controller-runtime util package has some helpers that do some pre-flight checks client-side when updating the owner references to prevent invalid references before applying them server-side. That tends to confirm they are not reported synchronously by the API server.

**Review by astefanutti — APPROVED** [review]
