### PR TITLE
fix(crd): Remove traits default values

### LINKED ISSUE #5060: Operator 2.2.0 does not spawn builder pod with strategy: pod
### What happened?

While:
- Setting up a new K8s cluster via Kind
- Deploying the Camel-K 2.2.0 operator (via Helm chart) with buildConfiguration strategy set to pod
- Applying a integration

I noticed that there were no builder pods created but the image was build inside the operator pod.

After creating a new cluster and using operator 2.1.0 helm chart / version, the operator spawned pods as expected.

Attached you find the logs of the operators as well as my helmfile snipped to deploy the operator.

[operator_2.1.0.log](https://github.com/apache/camel-k/files/13905921/operator_2.1.0.log)
[operator_2.2.0.log](https://github.com/apache/camel-k/files/13905922/operator_2.2.0.log)

(the error messages in the end should not matter i guess)

[Zulip-Chat](https://camel.zulipchat.com/#narrow/stream/257299-camel-k/topic/Operator.202.2E2.2E0.20does.20not.20spawn.20builder.20pod.20with.20strategy.3A.20pod)

Thanks :)

```repositories:
- name: incubator
  url: https://charts.helm.sh/incubator
- name: camel-k
  url: https://apache.github.io/camel-k/charts/
  
releases:
- name: camel-k-operator
  namespace: {{ .Values.namespaces.camelk }}
  chart: camel-k/camel-k
  version: 2.x.0 
  disableValidation: true
  labels:
    chapter: data
    package: camel-k
    component: base
  hooks:
  - events: ["preapply"]
    showlogs: true
    command: "kubectl"
    args: ["apply", "-n", "{{`{{.Values.namespaces.camelk}}`}}", "-f", "./templates"]
  - events: ["postuninstall"]
    showlogs: true
    command: "kubectl"
    args: ["delete", "-n", "{{`{{.Values.namespaces.camelk}}`}}", "-f", "./templates"]
  values:
  - operator:
      global: "true"
      resources:
        requests:
          cpu: 100m
          memory: 250Mi
    platform:
      build:
        registry:
          address: {{ env "K3d_REGISTRY_ENDPOINT" }}
          insecure: true
        buildConfiguration:
          strategy: pod
      traits:
        builder:
          tasksRequestCPU:
          - "builder:2000m"
          tasksRequestMemory:
          - "builder:2Gi"
```

### Steps to reproduce

1. Setup new cluster
2. Deploy operator 2.2.0 via Helm chart, set strategy to pod
3. See operator building the image in its container

### Relevant log output

_No response_

### Camel K version

2.2.0

### PR DESCRIPTION
**Pull request by gansheer**
Closes #5060 

* Rollback default values added by PR https://github.com/apache/camel-k/pull/4887 .
* Add non-regressions tests on traits to avoid having non-explicit values in integration test definitions

Note : should re-open #4726

**Release Note**
```release-note
fix(crd): Remove traits default values
```

### CODE REVIEW

File: e2e/common/config/config_test.go [hunk 1]
```diff
@@ -120,6 +122,16 @@ func TestRunConfigExamples(t *testing.T) {
 		Eventually(IntegrationPodPhase(ns, "property-secret-route"), TestTimeoutLong).Should(Equal(corev1.PodRunning))
 		Eventually(IntegrationConditionStatus(ns, "property-secret-route", v1.IntegrationConditionReady), TestTimeoutShort).Should(Equal(corev1.ConditionTrue))
 		Eventually(IntegrationLogs(ns, "property-secret-route"), TestTimeoutShort).Should(ContainSubstring("my-secret-external-value"))
+
+		// check integration schema does not contains unwanted default trait value.
+		gvk := schema.GroupVersionKind{Group: v1.SchemeGroupVersion.Group, Version: v1.SchemeGroupVersion.Version, Kind: v1.IntegrationKind}
```
Comment (squakez) [inline e2e/common/config/config_test.go:127]: I see this is duplicated everywhere. Create a test support function in order to avoid too much duplication and difficulty in code reading.

**Review by squakez — APPROVED** [review]
