### PR TITLE
fix(trait): ImagePullSecrets are not configured when the Integration is running

### LINKED ISSUE #2394: ImagePullSecrets are not configured when the Integration is running
The PullSecret trait only applies when the Integration is deploying. It should also apply when the Integration is running, to maintain the configuration of the Deployment `ImagePullSecrets`.

### PR DESCRIPTION
**Pull request by claudio4j**
Fix #2394

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by astefanutti — APPROVED** [review]
Thanks!

File: pkg/trait/pull_secret.go [hunk 1]
```diff
@@ -110,7 +110,7 @@ func (t *pullSecretTrait) Apply(e *Environment) error {
 			})
 		})
 	}
-	if util.IsTrue(t.ImagePullerDelegation) {
+	if util.IsTrue(t.ImagePullerDelegation) && e.IntegrationInPhase(v1.IntegrationPhaseDeploying) {
```
Comment (astefanutti) [inline pkg/trait/pull_secret.go:113]: Actually, thinking about this, I think we should refactor the `delegateImagePuller` method:
* Add the RoleBinding to the environment resources, instead of manually creating it
* Call the `delegateImagePuller` method in both deploying and running phase

That way, we follow the idiomatic way of managing resources, and let the _deployer_ and _gc_ do their duties.

**Review by astefanutti — CHANGES_REQUESTED** [review]

File: pkg/trait/pull_secret.go (hunk 1 above)
Comment (claudio4j) [reply pkg/trait/pull_secret.go]: Changes done, I found it better to remove `delegateImagePuller` method as it was not doing much.

**Review by astefanutti — APPROVED** [review]

File: pkg/trait/pull_secret.go (hunk 1 above)
Comment (astefanutti) [reply pkg/trait/pull_secret.go]: Thanks, I agree with you 👍🏼.
