### PR TITLE
fix(build): default jitpack to main

### LINKED ISSUE #2764: Jitpack still configured with `master` branch
https://github.com/apache/camel-k/blob/main/pkg/util/jitpack/jitpack.go#L28

### PR DESCRIPTION
**Pull request by squakez**
* Moved default from master to main
* Added some meaningful example

Closes #2764

**Release Note**
```release-note
fix(build): default jitpack to main
```

### CODE REVIEW

File: pkg/util/jitpack/jitpack.go [hunk 1]
```diff
@@ -24,10 +24,13 @@ import (
...
 const (
-	RepoURL       = "https://jitpack.io"
-	LatestVersion = "master-SNAPSHOT"
+	// RepoURL is the Jitpack repository url
+	RepoURL = "https://jitpack.io"
+	// DefaultVersion is the default branch/version to use
+	DefaultVersion = "main-SNAPSHOT"
 )
 
+// ToDependency converts a jitpack dependency into Depdendency struct
```
Comment (tadayosi) [inline pkg/util/jitpack/jitpack.go:33]: Not a big deal, but a small typo: `Depdendency` -> `Dependency`

**Review by tadayosi — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Review by astefanutti — APPROVED** [review]
Great!

**Comment by squakez** [comment]
CI is failing because #2742 not related to the change done here. I'll merge if no objections.
