### PR TITLE
fix(quarkus): build time properties into file

### LINKED ISSUE #5195: Builder property failure when using non xml tag characters
### What happened?

As we translate the builder properties into xml project properties, then, there is an error when we use characters not fitting the xml tag specification.

### Steps to reproduce

`kamel run test.yaml --build-property test.\"property\"=fail --dev`

### Relevant log output

```shell
camel-k-operator-5cdfc89cd8-tqr5m camel-k-operator {"level":"error","ts":"2024-02-28T10:48:16Z","logger":"camel-k.maven.build","msg":"[ERROR] Some problems were encountered while processing the POMs:\n[FATAL] Non-parseable POM /tmp/kit-cnfguqlmitks73fs1f3g-2157715289/maven/pom.xml: start tag unexpected character \" (position: TEXT seen ...</quarkus.package.type>\\n    <test.\"... @10:12)  @ line 10, column 12\n @ ","stacktrace":"github.com/apache/camel-k/v2/pkg/util/log.Logger.Error\n\tgithub.com/apache/camel-k/v2/pkg/util/log/log.go:81\ngithub.com/apache/camel-k/v2/pkg/util/maven.normalizeLog\n\tgithub.com/apache/camel-k/v2/pkg/util/maven/maven_log.go:83\ngithub.com/apache/camel-k/v2/pkg/util/maven.MavenLogHandler\n\tgithub.com/apache/camel-k/v2/pkg/util/maven/maven_log.go:54\ngithub.com/apache/camel-k/v2/pkg/util.scan\n\tgithub.com/apache/camel-k/v2/pkg/util/command.go:76\ngithub.com/apache/camel-k/v2/pkg/util.RunAndLog.func1\n\tgithub.com/apache/camel-k/v2/pkg/util/command.go:55\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.6.0/errgroup/errgroup.go:78"}
```

### Camel K version

_No response_

### PR DESCRIPTION
**Pull request by squakez**
Moving from maven based approach to a file approach in order to let be able to use any character which may be a limitation in pom.xml

Closes #5195

**Release Note**
```release-note
fix(quarkus): build time properties into file
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: pkg/builder/quarkus.go [hunk 1]
```diff
@@ -163,53 +158,6 @@ func GenerateQuarkusProjectCommon(runtimeVersion string, quarkusVersion string,
...
-		if strings.HasPrefix(key, "quarkus.camel.") {
-			buildProperties[key] = value
-		}
-	}
-
-	configuration := v1.PluginProperties{}
-	configuration.AddProperties("properties", buildProperties)
-
-	// Plugins
-	p.Build.Plugins = append(p.Build.Plugins,
```
Comment (claudio4j) [inline pkg/builder/quarkus.go:196]: Should the quarkus-maven-plugin be removed ?
The project will fail to materialize the quarkus-app.jar

File: pkg/builder/quarkus.go [hunk 2]
```diff
@@ -261,6 +201,39 @@ func BuildQuarkusRunnerCommon(ctx context.Context, mc maven.Context, project mav
...
+	// Fill with properties coming from user configuration
+	for k, v := range applicationProperties {
+		if _, err := f.WriteString(fmt.Sprintf("%s=%s\n", k, v)); err != nil {
+			return err
+		}
+	}
+	if err := f.Sync(); err != nil {
+		return err
+	}
+	w := bufio.NewWriter(f)
```
Comment (claudio4j) [inline pkg/builder/quarkus.go:230]: my knowledge of IO may be outdated, but I am curious why the buffered writer is created after the content was already written and synced to the file ?

File: pkg/builder/quarkus.go (hunk 1 above)
Comment (squakez) [reply pkg/builder/quarkus.go:196]: Should be fixed now. Thanks.

File: pkg/builder/quarkus.go (hunk 2 above)
Comment (squakez) [reply pkg/builder/quarkus.go:250]: Well spotted, thanks. It was a leftover.
