### PR TITLE
fix(cli) Duplicated trait set as modeline and kamel run parameters causes error

### LINKED ISSUE #2466: Duplicated trait set as modeline and kamel run parameters causes error
executing this command:

```
kamel run --name metrics --trait prometheus.enabled=true  Metrics.java -w --dependency mvn:com.github.openshift-integration:camel-k-example-metrics:1.0.0-SNAPSHOT
```

I got this message:

```
Modeline options have been loaded from source files
Full command: kamel run --name metrics --trait prometheus.enabled=true Metrics.java -w --dependency mvn:com.github.openshift-integration:camel-k-example-metrics:1.0.0-SNAPSHOT --trait=prometheus.enabled=true 
Error: 1 error(s) decoding:

* 'enabled' expected type 'bool', got unconvertible type '[]string'
```

Metrics.java is taken from: https://github.com/apache/camel-k/blob/main/e2e/yaks/openshift/monitoring/Metrics.java .
It seems the "enabled" property is both inferred from the integration and got from command line, causing a sort of double specification error ("type '[]string'").

### PR DESCRIPTION
**Pull request by claudio4j**
Fix #2466

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: e2e/common/files/JavaTraits.java [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+import org.apache.camel.builder.RouteBuilder;
+
+public class JavaTraits extends RouteBuilder {
```
Comment (astefanutti) [inline e2e/common/files/JavaTraits.java:22]: Would `e2e/cli` be a more appropriate location for this test?

File: pkg/cmd/run.go [hunk 2]
```diff
@@ -801,6 +800,8 @@ func resolvePodTemplate(ctx context.Context, templateSrc string, spec *v1.Integr
 func configureTraits(options []string, catalog *trait.Catalog) (map[string]v1.TraitSpec, error) {
 	traits := make(map[string]map[string]interface{})
 
+	// remove any duplicate trait parameters in case it is set as modeline or command line parameters
+	util.StringsSliceRemoveDuplicates(&options)
```
Comment (astefanutti) [inline pkg/cmd/run.go:804]: What is the precedence between modeline and CLI options? I think the CLI options should override duplicated ones from modeline?

**Review by astefanutti — COMMENTED** [review]
Thanks, I've left a couple of comments/questions.

File: e2e/common/files/JavaTraits.java (hunk 1 above)
Comment (claudio4j) [reply e2e/common/files/JavaTraits.java:22]: no problem.

File: pkg/cmd/run.go (hunk 2 above)
Comment (claudio4j) [reply pkg/cmd/run.go:804]: At this point there is no difference about the trait values, so the duplicate routine checks the trait name and value. I think it would be appropriate to check only the names, similar to the property key names, wdyt ?

Comment (claudio4j) [reply pkg/cmd/run.go]: Now the code checks for trait names only and the cli traits has precedence.

**Comment by claudio4j** [comment]
@oscerd or @nicolaferraro can you review and merge ?

**Comment by claudio4j** [comment]
retest

**Comment by nicolaferraro** [comment]
@claudio4j have you checled if it affect traits having multiple values.

E.g. if I want to set `knative.sink-channels` to `chan1` and `chan2`, can I run `-t knative.sink-channels=chan1 -t knative.sink-channels=chan2` ? Does it only apply to modeline vs command line params?

**Comment by claudio4j** [comment]
The precedence applies only to trait/property keys from modeline and cli and in the case you mentioned, the values are correctly applied as `[]string`, example
```
kamel run -o yaml files/JavaDuplicateParams.java -t knative.enabled=true -t knative.channel-sinks=chan1 -t knative.channel-sinks=chan2
```

The output
```
  traits:
    knative:
      configuration:
        channelSinks:
        - chan1
        - chan2
        enabled: true
```

**Review by nicolaferraro — APPROVED** [review]

**Comment by nicolaferraro** [comment]
There are test errors related to this PR

**Comment by claudio4j** [comment]
@nicolaferraro I fixed the e2e tests, can you review ? Thanks.

**Comment by claudio4j** [comment]
@nicolaferraro can you check if it's ok to merge this one  ?

**Review by nicolaferraro — APPROVED** [review]

**Review by nicolaferraro — APPROVED** [review]
