### PR TITLE
fix: kamel run -o incompatible with --dev

### LINKED ISSUE #3195: Kamel run -o incompatible with --dev
Running
```
kamel run ./examples/languages/Sample.java --dev -o yaml
```
Will produce an error like
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1d9b80f]

goroutine 1 [running]:
github.com/apache/camel-k/pkg/util/watch.HandleIntegrationStateChanges(0x2748458, 0xc000064280, 0x27829a0, 0xc0007f86c0, 0x0, 0xc000bb34c8, 0x0, 0x0, 0x0)
	github.com/apache/camel-k/pkg/util/watch/watch.go:35 +0x8f
github.com/apache/camel-k/pkg/cmd.(*runCmdOptions).waitForIntegrationReady(0xc000af0e00, 0xc00081b900, 0x27829a0, 0xc0007f86c0, 0x0, 0xc0007f86c0, 0x0, 0xc000848010)
	github.com/apache/camel-k/pkg/cmd/run.go:416 +0x9e
github.com/apache/camel-k/pkg/cmd.(*runCmdOptions).run(0xc000af0e00, 0xc00081b900, 0xc00044b2c0, 0x1, 0x4, 0x0, 0x0)
	github.com/apache/camel-k/pkg/cmd/run.go:343 +0x4be
github.com/spf13/cobra.(*Command).execute(0xc00081b900, 0xc00044b280, 0x4, 0x4, 0xc00081b900, 0xc00044b280)
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00081ac80, 0xc0007f9b80, 0xc00004c1e0, 0x6)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	github.com/apache/camel-k/cmd/kamel/main.go:47 +0x17d
```
We probably need to include a check to warn the user the two options are not compatible.

### PR DESCRIPTION
**Pull request by KuthumiPepple**
Closes #3195
@astefanutti @squakez I included a test first for the fix. For the fix, I added a check for both flags. If both flags are present, an error is returned with the error message written to the error writer. Please review and let me know if there are any more things I could do.

**Release Note**
```release-note
NONE
```

### CODE REVIEW

File: pkg/cmd/run.go [hunk 1]
```diff
@@ -243,6 +243,10 @@ func (o *runCmdOptions) validate() error {
 		return err
 	}
 
+	if o.OutputFormat != "" && o.Dev {
+		return errors.New("option '-o' is not compatible with '--dev'")
```
Comment (squakez) [inline pkg/cmd/run.go:247]: We better keep using the `fmt` package as we're doing for the rest of errors, ie `return fmt.Errorf(invalid label specification %s. Expected "<labelkey>=<labelvalue>", label)`

Comment (KuthumiPepple) [reply pkg/cmd/run.go:247]: Ok I'd use the `fmt` package

**Comment by KuthumiPepple** [comment]
I have implemented the change

File: pkg/cmd/run.go [hunk 2]
```diff
@@ -243,6 +243,10 @@ func (o *runCmdOptions) validate() error {
 		return err
 	}
 
+	if o.OutputFormat != "" && o.Dev {
+		return fmt.Errorf(`invalid dev specification "%t". Expected "--dev=false"`, o.Dev)
```
Comment (squakez) [inline pkg/cmd/run.go:247]: I think it won't be clear for the user why this is invalid. I guess something like `cannot use --dev with -o/--output options` would be clearer.

Comment (KuthumiPepple) [reply pkg/cmd/run.go:247]: Thanks, I'll amend and force push

**Review by squakez — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Please rebase on main, so it will be aligned and test will pass.

**Comment by KuthumiPepple** [comment]
> Please rebase on main, so it will be aligned and test will pass.

Done
