### PR TITLE
fix: Improve Knative trigger filter

### LINKED ISSUE #5446: Knative Trigger creation is only based on event type attribute
### Requirement

Creating a trigger is currently limited to just the event type. No other CloudEvent attributes or even extensions are being considered here:

https://github.com/apache/camel-k/blob/349dd37177e785128cf12b9dba194cd675d1e142/pkg/util/knative/knative.go#L103-L105

### Problem

Only triggers with event type are possible

### Proposal

make usage of othr attributes / extensions

### Open questions

_No response_

### LINKED ISSUE #5529: property "type" must be provided when reading from the Broker
### What happened?

Creating a logger-pipe that reads from the broker seems to not work:

```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: log-sink-pipe
spec:
  source:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: kamelet
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
```

In theory it should create a trigger that has no filter, which is valid

### Steps to reproduce

1. create knative broker
2. create a logger like above
3. see the logs

### Relevant log output

```shell
{"level":"info","ts":"2024-05-21T09:38:00Z","logger":"camel-k.controller.pipe","msg":"Initializing Pipe","request-namespace":"default","request-name":"log-sink-pipe","api-version":"camel.apache.org/v1","kind":"Pipe","ns":"default","name":"log-sink-pipe"}
{"level":"info","ts":"2024-05-21T09:38:00Z","logger":"camel-k.controller.pipe","msg":"State transition","request-namespace":"default","request-name":"log-sink-pipe","api-version":"camel.apache.org/v1","kind":"Pipe","ns":"default","name":"log-sink-pipe","phase-from":"","phase-to":"Error"}
{"level":"info","ts":"2024-05-21T09:38:00Z","logger":"camel-k.controller.pipe","msg":"Integration error","request-namespace":"default","request-name":"log-sink-pipe","api-version":"camel.apache.org/v1","kind":"Pipe","ns":"default","name":"log-sink-pipe","reason":"Couldn't create an Integration custom resource","error-message":"could not determine source URI: property \"type\" must be provided when reading from the Broker"}
{"level":"error","ts":"2024-05-21T09:38:00Z","msg":"Reconciler error","controller":"pipe-controller","object":{"name":"log-sink-pipe","namespace":"default"},"namespace":"default","name":"log-sink-pipe","reconcileID":"76ed504b-a166-4df7-b457-360c3f606dab","error":"could not determine source URI: property \"type\" must be provided when reading from the Broker","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.15.2/pkg/internal/controller/controller.go:226"}

```
```


### Camel K version

2.3.1

### LINKED ISSUE #5537: Unable to specify any CloudEvent attributes or extensions, except for `type`
### Requirement

Creating a `Pipe` that is reading from a **Knative Broker**, requires to set the `type` attribute of the CloudEvent, see #5529 for reference. This is than used when Camel-K creates a Knative `Trigger` and passed to the `spec.filter.attribues` of that `Trigger`

However it is not possible to provide any other CE metadata (e.g. defined attributes or extensions), such as:

```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: log-sink-pipe
spec:
  source:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: test-broker-2
    properties:
      type: com.corp.my.beer.source
      source: /bar
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
```

It would be nice if there would be a better support for any CE attribute/extension, and than being applied down to the `Trigger`, perhaps has as a custom propertie? So that Camel-k could create as flexible/powerful `Triggers`

### Problem

Camel-K seems to not support creating Knative Triggers with filter attributes, other than the `type` of the CloudEvent message.

On the pod of the pipe, I see this log:

```
2024-05-22 12:24:27,542 INFO  [org.apa.cam.k.Runtime] (main) Apache Camel K Runtime 3.8.1
2024-05-22 12:24:27,547 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2024-05-22 12:24:27,552 INFO  [org.apa.cam.mai.MainSupport] (main) Apache Camel (Main) 4.4.1 is starting
2024-05-22 12:24:27,610 INFO  [org.apa.cam.k.sup.SourcesSupport] (main) Loading routes from: SourceDefinition{name='camel-k-embedded-flow', language='yaml', type='source', location='file:/etc/camel/sources/camel-k-embedded-flow.yaml', }
2024-05-22 12:24:27,937 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: org.apache.camel.FailedToCreateRouteException: Failed to create route binding: Route(binding)[From[knative:event/com.corp.my.beer.source?ap... because of Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{source=/bar}]
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:85)
	at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:728)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:594)
	at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2385)
	at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:194)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:78)
	at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2021)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:105)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2040)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:212)
	at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:113)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:140)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{source=/bar}]
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:830)
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:730)
	at org.apache.camel.support.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:61)
	at org.apache.camel.reifier.AbstractReifier.resolveEndpoint(AbstractReifier.java:195)
	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:99)
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:79)
	... 30 more
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{source=/bar}]
	at org.apache.camel.support.DefaultComponent.validateParameters(DefaultComponent.java:302)
	at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:191)
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:796)
	... 35 more

2024-05-22 12:24:27,998 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.camel.FailedToCreateRouteException: Failed to create route binding: Route(binding)[From[knative:event/com.corp.my.beer.source?ap... because of Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{source=/bar}]
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:47)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
	... 13 more
Caused by: java.lang.RuntimeException: org.apache.camel.FailedToCreateRouteException: Failed to create route binding: Route(binding)[From[knative:event/com.corp.my.beer.source?ap... because of Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{source=/bar}]
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:65)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	... 15 more
Caused by: org.apache.camel.FailedToCreateRouteException: Failed to create route binding: Route(binding)[From[knative:event/com.corp.my.beer.source?ap... because of Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{source=/bar}]
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:85)
	at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:728)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:594)
	at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2385)
	at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:194)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:78)
	at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2021)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:105)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2040)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:212)
	at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:113)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:140)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	... 16 more
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{source=/bar}]
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:830)
	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:730)
	at org.apache.camel.support.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:61)
	at org.apache.camel.reifier.AbstractReifier.resolveEndpoint(AbstractReifier.java:195)
	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:99)
	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:79)
	... 30 more
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: knative://event/com.corp.my.beer.source?apiVersion=eventing.knative.dev%2Fv1&kind=Broker&name=test-broker-2&source=%2Fbar due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{source=/bar}]
	at org.apache.camel.support.DefaultComponent.validateParameters(DefaultComponent.java:302)
	at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:191)
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:796)
	... 35 more

```

### Proposal

_No response_

### Open questions

_No response_

### LINKED ISSUE #5577: Consistently support "cloudEventsType" property in Pipes source/sink
### Requirement

Consistently support property settings on both source and sink in Pipes when connecting with a Knative broker.

### Problem

When a Pipe references a Knative broker as a sink users are able to specify the CloudEvents event type using the `cloudEventsType` property setting. This controls the event type that is produced by the Pipe.

On the source side when the Pipe consumes the event stream from a Knative broker users need to use `type` property setting instead. This filters the event stream for events of a given type.

The different names of properties is misleading and we should consistently support the same settings on both source and sink when connecting with the Knative broker.

### Proposal

_No response_

### Open questions

_No response_

### PR DESCRIPTION
**Pull request by christophd**
- Fixes #5537: 
Support filter attributes other than event type (e.g. source, subject, extensions)
- Fixes #5529: 
Allows empty filter to consume the full event stream
- Fixes #5446: 
Knative Trigger creation is only based on event type attribute
- Fixes #5577: 
Consistently support "cloudEventsType" property in Pipes source/sink
- Update documentation and improve Knative Kamelet/Pipe user guide

**Release Note**
```release-note
fix(#5537): Support filter attributes other than event type
fix(#5529): Allows empty filter to consume the full event stream
fix(#5446): Knative Trigger creation is only based on event type attribute
fix(#5577): Consistently support "cloudEventsType" property in Pipes source/sink
```

### CODE REVIEW

File: pkg/trait/knative_test.go [hunk 1]
```diff
@@ -361,6 +362,204 @@ func TestKnativeTriggerConfiguration(t *testing.T) {
...
+	environment.Platform.ResyncStatusFullConfig()
+
+	// don't care about conditions in this unit test
+	_, err = traitCatalog.apply(&environment)
+
+	require.NoError(t, err)
+	assert.NotEmpty(t, environment.ExecutedTraits)
+	assert.NotNil(t, environment.GetTrait("knative"))
+
+	assert.NotNil(t, environment.Resources.GetKnativeTrigger(func(trigger *eventing.Trigger) bool {
```
Comment (squakez) [inline pkg/trait/knative_test.go:454]: Why not taking the explicit trigger and doing each assert specifically. If that fails we know exactly what's going on.

File: pkg/trait/knative_test.go [hunk 2]
```diff
@@ -361,6 +362,204 @@ func TestKnativeTriggerConfiguration(t *testing.T) {
...
```
Comment (squakez) [inline pkg/trait/knative_test.go:552]: Ditto

File: pkg/util/bindings/knative_ref.go [hunk 3]
```diff
@@ -93,26 +89,72 @@ func (k KnativeRefBindingProvider) Translate(ctx BindingContext, endpointCtx End
...
+	}
+
 	serviceURI = uri.AppendParameters(serviceURI, props)
-	return &Binding{
+	var binding = Binding{
 		URI: serviceURI,
-	}, nil
+	}
+
+	if len(filterExpressions) > 0 {
```
Comment (squakez) [inline pkg/util/bindings/knative_ref.go:143]: I am not sure it is a good way to configure it. The binding should know nothing about traits and its configuration I think.

**Review by squakez — COMMENTED** [review]
I have some design doubt about certain coupling we're adding. I need to review this deeply to understand what's the design implication of such change.

**Comment by squakez** [comment]
BTW, I think it would be wiser to split each issue you're fixing in separate PR. Maybe some of them can be merged straight away. If there is some code change in common for each, maybe you can start with a first PR and then issue any dependant PR once the others are approved and merged.

File: pkg/util/bindings/knative_ref.go (hunk 3 above)
Comment (christophd) [reply pkg/util/bindings/knative_ref.go:143]: I think the binding is supposed to adjust/configure the traits by design as it is part of the binding interface API and the trait config set by the binding explicitly gets merged into the integration traits.

See https://github.com/apache/camel-k/blob/main/pkg/util/bindings/api.go#L41

**Comment by christophd** [comment]
Sorry, for the bigger PR. Yes, I thought about splitting into multiple PRs but it all somehow touches the same bits so I kept it in one single PR. Please let me know if it works for you as I am having a look into the failing E2E tests right now

File: pkg/util/bindings/knative_ref.go (hunk 3 above)
Comment (squakez) [reply pkg/util/bindings/knative_ref.go:143]: Yes, I think the original idea was to use a way to represent certain options in order to later merge in the Integration [1] (ie, knative trait only). However, this changed when we have done the trait refactoring, creating a direct dependency between traits and bindings [2]. This was in fact only used in KnativeURI translator so far. I have the feeling that we should rework this part and find a different approach instead of extending a potential wrong design. What I mean is that the "trait" concept is an Integration thing and extending it widely creates coupling we can regret in the future. @lburgazzoli wdyt?

[1] https://github.com/apache/camel-k/commit/19b66cffb432f98f8e29ca0bf71e6112f375c989#diff-abb6a6ae31c506ba2b634a29eba8930cd19766cdec4d7d3aae43fbc3b4a08996
[2] https://github.com/apache/camel-k/commit/a92aaa405cf8a38a722c476251d04b99221f9682#diff-abb6a6ae31c506ba2b634a29eba8930cd19766cdec4d7d3aae43fbc3b4a08996

**Comment by squakez** [comment]
> Sorry, for the bigger PR. Yes, I thought about splitting into multiple PRs but it all somehow touches the same bits so I kept it in one single PR. Please let me know if it works for you as I am having a look into the failing E2E tests right now

No problem. I say more in the interest to maintain separate discussions and let the other fixes to go through independently.

**Comment by christophd** [comment]
@squakez all tests are green now. I have also added some E2E test to verify the different Knative trigger possibilities (e.g. no filter, filter by ce-source and so on)

In terms of design considerations I think the binding provider is meant to create/configure the integration from a Pipe that may reference other K8s resources. The binding provider translates these resource references into Camel components and the YAML route DSL that is being used in the integration. The traits are part of the integration so the binding provider has access to it, which is not a new design introduced in this PR.

We can open a new issue to discuss this current design if you want. WDYT?

**Comment by squakez** [comment]
Please, verify if @lburgazzoli can provide his thoughts about this before going ahead. Thanks.

**Comment by lburgazzoli** [comment]
Does it also relate to https://github.com/apache/camel-k/issues/3378 ?

**Comment by christophd** [comment]
@lburgazzoli this PR does not include the support for the extended triggers in Knative. At the moment the extended triggers are experimental and we would need more logic on the Knative trait to support the extended filters for the trigger. 

But yes, the Pipe configuring the extended Knative triggers via traits is one possible option.

**Comment by christophd** [comment]
> about the knative trait, the same as above can apply as there (maybe) are some conflicting properties maybe ? i.e. what happen if you set a filter for a non broker resource?

I have checked in the code and Camel K will create the trigger only when using the broker resource as a source. when referencing a Knative channel resource for instance Camel K will not create the trigger and it is assumed that the channel and the trigger are present already.

So setting the trigger filter on the trait is only valid for broker type events. This is the result of us having a single Knative trait config for multiple Knative resources (broker, channel, service) as a source/sink. Again, this needs to be made clear in the documentation. I will take care of it (probably in a separate PR)
