### PR TITLE
camel-rest should load automatically for routes using Rest DSL

### LINKED ISSUE #862: camel-rest should load automatically for routes using Rest DSL
Currently `examples/RestWithRestlet.java` fails unless `--dependency=camel-rest` is explicitly set:
```
$ kamel run --name=rest-with-restlet --dependency=camel-restlet examples/RestWithRestlet.java --dev
...
[1] Exception in thread "main" org.apache.camel.FailedToCreateRouteException: Failed to create route route2: Route(route2)[From[rest://get:/hello?consumerComponentName=r... because of Failed to resolve endpoint: rest://get:/hello?consumerComponentName=restlet&routeId=route2 due to: No component found with scheme: rest
[1] 	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:100)
[1] 	at org.apache.camel.impl.DefaultModel.start(DefaultModel.java:346)
[1] 	at org.apache.camel.impl.DefaultModel.startRoute(DefaultModel.java:320)
[1] 	at org.apache.camel.impl.DefaultModel.startRouteDefinitions(DefaultModel.java:313)
[1] 	at org.apache.camel.impl.DefaultModel.startRouteDefinitions(DefaultModel.java:292)
[1] 	at org.apache.camel.impl.AbstractModelCamelContext.startRouteDefinitions(AbstractModelCamelContext.java:330)
[1] 	at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:2555)
[1] 	at org.apache.camel.impl.engine.AbstractCamelContext.lambda$doStart$2(AbstractCamelContext.java:2387)
[1] 	at org.apache.camel.impl.engine.AbstractCamelContext.doWithDefinedClassLoader(AbstractCamelContext.java:2404)
[1] 	at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2385)
[1] 	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:97)
[1] 	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2296)
[1] 	at org.apache.camel.main.Main.doStart(Main.java:117)
[1] 	at org.apache.camel.support.service.ServiceSupport.start(ServiceSupport.java:97)
[1] 	at org.apache.camel.main.MainSupport.run(MainSupport.java:196)
[1] 	at org.apache.camel.k.main.ApplicationRuntime.run(ApplicationRuntime.java:70)
[1] 	at org.apache.camel.k.main.Application.main(Application.java:44)
[1] Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: rest://get:/hello?consumerComponentName=restlet&routeId=route2 due to: No component found with scheme: rest
[1] 	at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:779)
[1] 	at org.apache.camel.support.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:55)
[1] 	at org.apache.camel.impl.engine.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:114)
[1] 	at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:334)
[1] 	at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:95)
[1] 	... 16 more
```

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #862

### CODE REVIEW

File: pkg/metadata/metadata.go [hunk 1]
```diff
@@ -31,39 +31,32 @@ import (
...
-		deps[d] = true
-	}
-	allDependencies := make([]string, 0)
-	for k := range deps {
-		allDependencies = append(allDependencies, k)
-	}
-	sort.Strings(allDependencies)
+	d := strset.Union(m1.Dependencies, m2.Dependencies)
+
+	f := make([]string, len(m1.FromURIs)+len(m2.FromURIs))
```
Comment (nicolaferraro) [inline pkg/metadata/metadata.go]:
```suggestion
	f := make([]string, 0, len(m1.FromURIs)+len(m2.FromURIs))
```

File: pkg/metadata/metadata.go [hunk 2]
```diff
@@ -31,39 +31,32 @@ import (
...
+	f = append(f, m1.FromURIs...)
+	f = append(f, m2.FromURIs...)
+
+	t := make([]string, len(m1.ToURIs)+len(m2.ToURIs))
```
Comment (nicolaferraro) [inline pkg/metadata/metadata.go]:
```suggestion
	t := make([]string, 0, len(m1.ToURIs)+len(m2.ToURIs))
```

**Comment by lburgazzoli** [comment]
fixed
