### PR TITLE
fix(trait): Camel trait as IntegrationKit

### LINKED ISSUE #3758: Runtime trait failure
When we use `-t camel.runtime-version` property, the Integration got stuck and doesn't run.
```
$ kamel run /tmp/Hello.java --dev -x test -t camel.runtime-version=1.13.0
Integration "hello" created
Condition "IntegrationPlatformAvailable" is "True" for Integration hello: default/test
Progress: integration "hello" in phase Initialization
Integration "hello" in phase "Initialization"
Progress: integration "hello" in phase Building Kit
Integration "hello" in phase "Building Kit"
Condition "IntegrationKitAvailable" is "False" for Integration hello: creating a new integration kit
Integration Kit "kit-cd8h447viejc73dj81fg", created by Integration "hello", changed phase to "Build Submitted"
Build "kit-cd8h447viejc73dj81fg", created by Integration "hello", changed phase to "Scheduling"
Build "kit-cd8h447viejc73dj81fg", created by Integration "hello", changed phase to "Pending"
Build "kit-cd8h447viejc73dj81fg", created by Integration "hello", changed phase to "Running"
Integration Kit "kit-cd8h447viejc73dj81fg", created by Integration "hello", changed phase to "Build Running"
Build "kit-cd8h447viejc73dj81fg", created by Integration "hello", changed phase to "Succeeded"
Integration Kit "kit-cd8h447viejc73dj81fg", created by Integration "hello", changed phase to "Ready"
```

### PR DESCRIPTION
**Pull request by squakez**
Closes #3758

**Release Note**
```release-note
fix(trait): Camel trait as IntegrationKit
```

### CODE REVIEW

File: pkg/apis/camel/v1/integrationkit_types.go [hunk 1]
```diff
@@ -77,7 +77,8 @@ type IntegrationKitTraits struct {
 	Quarkus *trait.QuarkusTrait `property:"quarkus" json:"quarkus,omitempty"`
 	// The Registry trait sets up Maven to use the Image registry as a Maven repository.
 	Registry *trait.RegistryTrait `property:"registry" json:"registry,omitempty"`
-
+	// The Camel trait sets up Camel configuration.
+	Camel *trait.CamelTrait `property:"camel" json:"camel,omitempty"`
```
Comment (tadayosi) [inline pkg/apis/camel/v1/integrationkit_types.go:81]: Nitpick: It'd be better to keep alphabetical order, which means Camel should be put between Builder and Quarkus.

File: pkg/trait/trait_test.go [hunk 2]
```diff
@@ -457,7 +457,7 @@ func TestConfigureVolumesAndMountsBinaryAndTextResources(t *testing.T) {
 
 func TestOnlySomeTraitsInfluenceBuild(t *testing.T) {
 	c := NewTraitTestCatalog()
-	buildTraits := []string{"builder", "quarkus", "registry"}
+	buildTraits := []string{"builder", "quarkus", "registry", "camel"}
```
Comment (tadayosi) [inline pkg/trait/trait_test.go:460]: Same here.

**Review by tadayosi — COMMENTED** [review]
Small nitpick but otherwise LGTM.

**Review by oscerd — APPROVED** [review]
