### PR TITLE
fix: redirect ouput and errors to appropriate writer

### LINKED ISSUE #2773: Get rid of `fmt.Print...()` methods
In particular for `cmd` package, we should redirect the output to the proper output writer.

### PR DESCRIPTION
**Pull request by KuthumiPepple**
Closes #2773 
fmt.Print...() methods have been removed where applicable and outputs and error messages are now being written to the appropriate Writers. @astefanutti please review

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by tadayosi — APPROVED** [review]

**Comment by tadayosi** [comment]
There are linter validation errors. Please fix them.

**Review by oscerd — APPROVED** [review]

File: e2e/support/test_support.go [hunk 1]
```diff
@@ -1719,9 +1719,9 @@ func UserCleanup() {
 		command.Stderr = os.Stderr
 		command.Stdout = os.Stdout
 		if err := command.Run(); err != nil {
-			fmt.Printf("An error occurred during user cleanup command execution: %v\n", err)
+			fmt.Fprintf(command.Stderr, "An error occurred during user cleanup command execution: %v\n", err)
```
Comment (astefanutti) [inline e2e/support/test_support.go:1722]: Could be replaced with `Fprintln`.

File: e2e/support/test_support.go [hunk 2]
```diff
@@ -1719,9 +1719,9 @@ func UserCleanup() {
...
 		} else {
-			fmt.Printf("User cleanup command completed successfully\n")
+			fmt.Fprintf(command.Stdout, "User cleanup command completed successfully\n")
```
Comment (astefanutti) [inline e2e/support/test_support.go:1724]: Could be replaced with `Fprintln`.

File: pkg/cmd/bind.go [hunk 3]
```diff
@@ -219,9 +219,9 @@ func (o *bindCmdOptions) run(cmd *cobra.Command, args []string) error {
 	}
 
 	if !existed {
-		fmt.Printf("kamelet binding \"%s\" created\n", name)
+		fmt.Fprintf(cmd.OutOrStdout(), "kamelet binding \"%s\" created\n", name)
```
Comment (astefanutti) [inline pkg/cmd/bind.go:222]: Could be replaced with `Fprintln`.

File: pkg/cmd/bind.go [hunk 4]
```diff
@@ -219,9 +219,9 @@ func (o *bindCmdOptions) run(cmd *cobra.Command, args []string) error {
...
 	} else {
-		fmt.Printf("kamelet binding \"%s\" updated\n", name)
+		fmt.Fprintf(cmd.OutOrStdout(), "kamelet binding \"%s\" updated\n", name)
```
Comment (astefanutti) [inline pkg/cmd/bind.go:224]: Could be replaced with `Fprintln`.

File: pkg/cmd/run.go [hunk 5]
```diff
@@ -615,10 +615,10 @@ func (o *runCmdOptions) createOrUpdateIntegration(cmd *cobra.Command, c client.C
 
 	if existing == nil {
 		err = c.Create(o.Context, integration)
-		fmt.Printf("Integration \"%s\" created\n", name)
+		fmt.Fprintf(cmd.OutOrStdout(), "Integration \"%s\" created\n", name)
```
Comment (astefanutti) [inline pkg/cmd/run.go:618]: Could be replaced with `Fprintln`.

File: pkg/cmd/run.go [hunk 6]
```diff
@@ -615,10 +615,10 @@ func (o *runCmdOptions) createOrUpdateIntegration(cmd *cobra.Command, c client.C
...
 	} else {
 		err = c.Patch(o.Context, integration, ctrl.MergeFromWithOptions(existing, ctrl.MergeFromWithOptimisticLock{}))
-		fmt.Printf("Integration \"%s\" updated\n", name)
+		fmt.Fprintf(cmd.OutOrStdout(), "Integration \"%s\" updated\n", name)
```
Comment (astefanutti) [inline pkg/cmd/run.go:621]: Could be replaced with `Fprintln`.

File: pkg/cmd/run_help.go [hunk 7]
```diff
@@ -43,20 +44,20 @@ func hashFrom(contents ...[]byte) string {
...
 }
 
-func parseConfigAndGenCm(ctx context.Context, c client.Client, config *resource.Config, integration *v1.Integration, enableCompression bool) (*corev1.ConfigMap, error) {
+func parseConfigAndGenCm(ctx context.Context, cmd *cobra.Command, c client.Client, config *resource.Config, integration *v1.Integration, enableCompression bool) (*corev1.ConfigMap, error) {
 	switch config.StorageType() {
 	case resource.StorageTypeConfigmap:
 		cm := kubernetes.LookupConfigmap(ctx, c, integration.Namespace, config.Name())
 		if cm == nil {
-			fmt.Printf("Warn: %s Configmap not found in %s namespace, make sure to provide it before the Integration can run\n",
+			fmt.Fprintf(cmd.ErrOrStderr(), "Warn: %s Configmap not found in %s namespace, make sure to provide it before the Integration can run\n",
```
Comment (astefanutti) [inline pkg/cmd/run_help.go:52]: Could be replaced with `Fprintln`.

File: pkg/cmd/run_help.go [hunk 8]
```diff
@@ -43,20 +44,20 @@ func hashFrom(contents ...[]byte) string {
...
 				config.Name(), integration.Namespace)
 		} else if config.ContentType() != resource.ContentTypeData && cm.BinaryData != nil {
 			return nil, fmt.Errorf("you cannot provide a binary config, use a text file instead")
 		}
 	case resource.StorageTypeSecret:
 		secret := kubernetes.LookupSecret(ctx, c, integration.Namespace, config.Name())
 		if secret == nil {
-			fmt.Printf("Warn: %s Secret not found in %s namespace, make sure to provide it before the Integration can run\n",
+			fmt.Fprintf(cmd.ErrOrStderr(), "Warn: %s Secret not found in %s namespace, make sure to provide it before the Integration can run\n",
```
Comment (astefanutti) [inline pkg/cmd/run_help.go:60]: Could be replaced with `Fprintln`.

File: pkg/cmd/uninstall.go [hunk 9]
```diff
@@ -186,21 +186,21 @@ func (o *uninstallCmdOptions) uninstallOperator(ctx context.Context, c client.Cl
...
 	if !o.SkipCrd || o.UninstallAll {
 		if err := o.uninstallCrd(ctx, c); err != nil {
 			if k8serrors.IsForbidden(err) {
-				return createActionNotAuthorizedError()
+				return createActionNotAuthorizedError(cmd)
 			}
 			return err
 		}
-		fmt.Printf("Camel K Custom Resource Definitions removed from cluster\n")
+		fmt.Fprintf(cmd.OutOrStdout(), "Camel K Custom Resource Definitions removed from cluster\n")
```
Comment (astefanutti) [inline pkg/cmd/uninstall.go:197]: Could be replaced with `Fprintln`.

File: pkg/cmd/uninstall.go [hunk 10]
```diff
@@ -209,71 +209,71 @@ func (o *uninstallCmdOptions) uninstallClusterWideResources(ctx context.Context,
...
 }
 
-func (o *uninstallCmdOptions) uninstallNamespaceRoles(ctx context.Context, c client.Client) error {
+func (o *uninstallCmdOptions) uninstallNamespaceRoles(cmd *cobra.Command, ctx context.Context, c client.Client) error {
 	if !o.SkipRoleBindings {
 		if err := o.uninstallRoleBindings(ctx, c); err != nil {
 			return err
 		}
-		fmt.Printf("Camel K Role Bindings removed from namespace %s\n", o.Namespace)
+		fmt.Fprintf(cmd.OutOrStdout(), "Camel K Role Bindings removed from namespace %s\n", o.Namespace)
```
Comment (astefanutti) [inline pkg/cmd/uninstall.go:237]: Could be replaced with `Fprintln`.

File: pkg/cmd/uninstall.go [hunk 11]
```diff
@@ -209,71 +209,71 @@ func (o *uninstallCmdOptions) uninstallClusterWideResources(ctx context.Context,
...
 	}
 
 	if !o.SkipRoles {
 		if err := o.uninstallRoles(ctx, c); err != nil {
 			return err
 		}
-		fmt.Printf("Camel K Roles removed from namespace %s\n", o.Namespace)
+		fmt.Fprintf(cmd.OutOrStdout(), "Camel K Roles removed from namespace %s\n", o.Namespace)
```
Comment (astefanutti) [inline pkg/cmd/uninstall.go:244]: Could be replaced with `Fprintln`.

File: pkg/cmd/uninstall.go [hunk 12]
```diff
@@ -209,71 +209,71 @@ func (o *uninstallCmdOptions) uninstallClusterWideResources(ctx context.Context,
...
 	}
 
 	if !o.SkipServiceAccounts {
 		if err := o.uninstallServiceAccounts(ctx, c); err != nil {
 			return err
 		}
-		fmt.Printf("Camel K Service Accounts removed from namespace %s\n", o.Namespace)
+		fmt.Fprintf(cmd.OutOrStdout(), "Camel K Service Accounts removed from namespace %s\n", o.Namespace)
```
Comment (astefanutti) [inline pkg/cmd/uninstall.go:251]: Could be replaced with `Fprintln`.

File: pkg/cmd/uninstall.go [hunk 13]
```diff
@@ -209,71 +209,71 @@ func (o *uninstallCmdOptions) uninstallClusterWideResources(ctx context.Context,
...
 }
 
-func (o *uninstallCmdOptions) uninstallNamespaceResources(ctx context.Context, c client.Client) error {
+func (o *uninstallCmdOptions) uninstallNamespaceResources(cmd *cobra.Command, ctx context.Context, c client.Client) error {
 	if !o.SkipConfigMaps {
 		if err := o.uninstallConfigMaps(ctx, c); err != nil {
 			return err
 		}
-		fmt.Printf("Camel K Config Maps removed from namespace %s\n", o.Namespace)
+		fmt.Fprintf(cmd.OutOrStdout(), "Camel K Config Maps removed from namespace %s\n", o.Namespace)
```
Comment (astefanutti) [inline pkg/cmd/uninstall.go:262]: Could be replaced with `Fprintln`.

File: pkg/cmd/uninstall.go [hunk 14]
```diff
@@ -209,71 +209,71 @@ func (o *uninstallCmdOptions) uninstallClusterWideResources(ctx context.Context,
...
 	}
 
 	if !o.SkipRegistrySecret {
 		if err := o.uninstallRegistrySecret(ctx, c); err != nil {
 			return err
 		}
-		fmt.Printf("Camel K Registry Secret removed from namespace %s\n", o.Namespace)
+		fmt.Fprintf(cmd.OutOrStdout(), "Camel K Registry Secret removed from namespace %s\n", o.Namespace)
```
Comment (astefanutti) [inline pkg/cmd/uninstall.go:269]: Could be replaced with `Fprintln`.

File: pkg/cmd/util_containerization.go [hunk 15]
```diff
@@ -192,7 +196,7 @@ func createAndBuildIntegrationImage(ctx context.Context, containerRegistry strin
 	cmd.Stdout = stdout
 
 	// Output executed command.
-	fmt.Printf("Executing: %s\n", strings.Join(cmd.Args, " "))
+	fmt.Fprintf(cmd.Stdout, "Executing: %s\n", strings.Join(cmd.Args, " "))
```
Comment (astefanutti) [inline pkg/cmd/util_containerization.go:199]: Could be replaced with `Fprintln`.

File: pkg/cmd/util_containerization.go [hunk 16]
```diff
@@ -94,8 +94,12 @@ func createAndBuildBaseImage(ctx context.Context) error {
 	args := docker.BuildBaseImageArgs()
 	cmd := exec.CommandContext(ctx, "docker", args...)
 
+	// Set stdout and stderr.
+	cmd.Stdout = stdout
+	cmd.Stderr = stderr
+
 	// Output executed command.
-	fmt.Printf("Executing: %s\n", strings.Join(cmd.Args, " "))
+	fmt.Fprintf(cmd.Stdout, "Executing: %s\n", strings.Join(cmd.Args, " "))
```
Comment (astefanutti) [inline pkg/cmd/util_containerization.go:102]: Could be replaced with `Fprintln`.

File: pkg/cmd/util_commands.go [hunk 17]
```diff
@@ -108,7 +108,7 @@ func RunLocalIntegrationRunCommand(ctx context.Context, properties []string, dep
 	}
 
 	// Output command we are about to run.
-	fmt.Printf("Executing: %s\n", strings.Join(cmd.Args, " "))
+	fmt.Fprintf(cmd.Stdout, "Executing: %s\n", strings.Join(cmd.Args, " "))
```
Comment (astefanutti) [inline pkg/cmd/util_commands.go:111]: Could be replaced with `Fprintln`.

File: pkg/cmd/uninstall.go [hunk 18]
```diff
@@ -209,71 +209,71 @@ func (o *uninstallCmdOptions) uninstallClusterWideResources(ctx context.Context,
...
 	}
 
 	if !o.SkipKamelets {
 		if err := o.uninstallKamelets(ctx, c); err != nil {
 			return err
 		}
-		fmt.Printf("Camel K platform Kamelets removed from namespace %s\n", o.Namespace)
+		fmt.Fprintf(cmd.OutOrStdout(), "Camel K platform Kamelets removed from namespace %s\n", o.Namespace)
```
Comment (astefanutti) [inline pkg/cmd/uninstall.go:276]: Could be replaced with `Fprintln`.

File: pkg/cmd/util_containerization.go [hunk 19]
```diff
@@ -225,7 +229,7 @@ func runIntegrationImage(ctx context.Context, image string, stdout, stderr io.Wr
 	cmd.Stdout = stdout
 
 	// Output executed command.
-	fmt.Printf("Executing: %s\n", strings.Join(cmd.Args, " "))
+	fmt.Fprintf(cmd.Stdout, "Executing: %s\n", strings.Join(cmd.Args, " "))
```
Comment (astefanutti) [inline pkg/cmd/util_containerization.go:232]: Could be replaced with `Fprintln`.

File: pkg/cmd/util_dependencies.go [hunk 20]
```diff
@@ -230,37 +231,37 @@ func createCamelCatalog(ctx context.Context) (*camel.RuntimeCatalog, error) {
...
 		if err != nil {
 			return err
 		}
 	} else {
 		// Print output in text form
-		fmt.Println("dependencies:")
+		fmt.Fprintln(cmd.OutOrStdout(), "dependencies:")
 		for _, dep := range dependencies {
-			fmt.Printf("%v\n", dep)
+			fmt.Fprintf(cmd.OutOrStdout(), "%v\n", dep)
```
Comment (astefanutti) [inline pkg/cmd/util_dependencies.go:244]: Could be replaced with `Fprintln`.

File: pkg/cmd/version.go [hunk 21]
```diff
@@ -171,15 +171,15 @@ func operatorVersion(ctx context.Context, c client.Client, namespace string) (st
 	return infos[infoVersion], nil
 }
 
-func compatibleVersions(aVersion, bVersion string) bool {
+func compatibleVersions(aVersion, bVersion string, cmd *cobra.Command) bool {
 	a, err := semver.NewVersion(aVersion)
 	if err != nil {
-		fmt.Printf("Could not parse %s (error: %s)\n", a, err)
+		fmt.Fprintf(cmd.ErrOrStderr(), "Could not parse %s (error: %s)\n", a, err)
```
Comment (astefanutti) [inline pkg/cmd/version.go:177]: Could be replaced with `Fprintln`.

File: pkg/cmd/version.go [hunk 22]
```diff
@@ -171,15 +171,15 @@ func operatorVersion(ctx context.Context, c client.Client, namespace string) (st
...
 		return false
 	}
 	b, err := semver.NewVersion(bVersion)
 	if err != nil {
-		fmt.Printf("Could not parse %s (error: %s)\n", b, err)
+		fmt.Fprintf(cmd.ErrOrStderr(), "Could not parse %s (error: %s)\n", b, err)
```
Comment (astefanutti) [inline pkg/cmd/version.go:182]: Could be replaced with `Fprintln`.

File: e2e/support/test_support.go (hunk 1 above)
Comment (astefanutti) [inline e2e/support/test_support.go:1722]: In that case, I think it's more appropriate to use the test logger with `t.Logf`.

File: e2e/support/test_support.go (hunk 2 above)
Comment (astefanutti) [inline e2e/support/test_support.go:1724]: In that case, I think it's more appropriate to use the test logger with `t.Logf`.

File: e2e/support/test_support.go (hunk 1 above)
Comment (KuthumiPepple) [reply e2e/support/test_support.go:1722]: Ok. I'd make the change

Comment (KuthumiPepple) [reply e2e/support/test_support.go:1722]: Yes that makes sense. I'd use the test logger

File: pkg/cmd/delete.go [hunk 23]
```diff
@@ -139,14 +139,14 @@ func getIntegration(ctx context.Context, c client.Client, name string, namespace
...
-func deleteIntegration(ctx context.Context, c client.Client, integration *v1.Integration) error {
+func deleteIntegration(cmd *cobra.Command, ctx context.Context, c client.Client, integration *v1.Integration) error {
 	deleted, binding, err := deleteKameletBindingIfExists(ctx, c, integration)
 	if err != nil {
 		return err
 	}
 	if deleted {
 		// Deleting KameletBinding will automatically clean up the integration
-		fmt.Println("KameletBinding " + binding + " deleted")
+		fmt.Fprintln(cmd.OutOrStdout(),"KameletBinding " + binding + " deleted")
```
Comment (squakez) [inline pkg/cmd/delete.go:149]: Missing space before the "KameletBinding" parameter.

File: pkg/cmd/rebuild.go [hunk 24]
```diff
@@ -69,7 +69,7 @@ func (o *rebuildCmdOptions) rebuild(_ *cobra.Command, args []string) error {
 		return err
 	}
 
-	fmt.Printf("%d integrations have been rebuilt\n", len(integrations))
+	fmt.Fprintf(cmd.OutOrStdout(),"%d integrations have been rebuilt\n", len(integrations))
```
Comment (squakez) [inline pkg/cmd/rebuild.go:72]: Another missing space. Likely you want to run `gofmt` to fix all formatting errors.

File: pkg/cmd/uninstall.go [hunk 25]
```diff
@@ -209,71 +209,71 @@ func (o *uninstallCmdOptions) uninstallClusterWideResources(ctx context.Context,
...
 		}
-		fmt.Printf("Camel K Cluster Roles removed from cluster\n")
+		fmt.Fprintf(cmd.OutOrStdout(), "Camel K Cluster Roles removed from cluster\n")
 	}
 
 	return nil
 }
 
-func (o *uninstallCmdOptions) uninstallNamespaceRoles(ctx context.Context, c client.Client) error {
+func (o *uninstallCmdOptions) uninstallNamespaceRoles(cmd *cobra.Command, ctx context.Context, c client.Client) error {
```
Comment (squakez) [inline pkg/cmd/uninstall.go:232]: Lint error, please fix accordingly.

File: pkg/cmd/util_dependencies.go [hunk 26]
```diff
@@ -230,37 +231,37 @@ func createCamelCatalog(ctx context.Context) (*camel.RuntimeCatalog, error) {
...
 		}
-		fmt.Print(string(data))
+		fmt.Fprint(cmd.OutOrStdout(), string(data))
 	case "json":
 		data, err := util.DependenciesToJSON(dependencies)
 		if err != nil {
 			return err
 		}
-		fmt.Print(string(data))
+		fmt.Fprint(cmd.OutOrStdout(),string(data))
```
Comment (squakez) [inline pkg/cmd/util_dependencies.go:264]: Lint error, please fix accordingly.

File: e2e/support/test_support.go (hunk 1 above)
Comment (KuthumiPepple) [reply e2e/support/test_support.go:1722]: Looking at this again, `Fprintln` doesn't accept a format string. Using `Fprintln` would mean doing away with the formatting. Isn't that inportant?

Comment (astefanutti) [reply e2e/support/test_support.go:1722]: `Fprintln` operands are appended with white spaces, e.g.:

```golang
fmt.Fprintf(command.Stderr, "An error occurred during user cleanup command execution: %v\n", err)
```

Can be turned into:

```golang
fmt.Fprintln(command.Stderr, "An error occurred during user cleanup command execution:", err.Error())
```

I think for all the statements where formatting is actually used for appending strings, then `Fprintln` is more appropriate.

Comment (KuthumiPepple) [reply e2e/support/test_support.go:1722]: Ok thank you. I'll use that

File: e2e/support/test_support.go (hunk 2 above)
Comment (KuthumiPepple) [reply e2e/support/test_support.go:1724]: Done

File: pkg/cmd/bind.go (hunk 3 above)
Comment (KuthumiPepple) [reply pkg/cmd/bind.go:222]: Done

File: pkg/cmd/run.go (hunk 5 above)
Comment (KuthumiPepple) [reply pkg/cmd/run.go:618]: Done

File: pkg/cmd/run.go (hunk 6 above)
Comment (KuthumiPepple) [reply pkg/cmd/run.go:621]: Done

File: pkg/cmd/run_help.go (hunk 7 above)
Comment (KuthumiPepple) [reply pkg/cmd/run_help.go:52]: Done

File: pkg/cmd/run_help.go (hunk 8 above)
Comment (KuthumiPepple) [reply pkg/cmd/run_help.go:60]: Done

File: pkg/cmd/uninstall.go (hunk 9 above)
Comment (KuthumiPepple) [reply pkg/cmd/uninstall.go:197]: Done

File: pkg/cmd/uninstall.go (hunk 10 above)
Comment (KuthumiPepple) [reply pkg/cmd/uninstall.go:237]: Done

File: pkg/cmd/uninstall.go (hunk 11 above)
Comment (KuthumiPepple) [reply pkg/cmd/uninstall.go:244]: Done

File: pkg/cmd/uninstall.go (hunk 12 above)
Comment (KuthumiPepple) [reply pkg/cmd/uninstall.go:251]: Done

File: pkg/cmd/uninstall.go (hunk 13 above)
Comment (KuthumiPepple) [reply pkg/cmd/uninstall.go:262]: Done

File: pkg/cmd/uninstall.go (hunk 14 above)
Comment (KuthumiPepple) [reply pkg/cmd/uninstall.go:269]: Done

File: pkg/cmd/util_containerization.go (hunk 15 above)
Comment (KuthumiPepple) [reply pkg/cmd/util_containerization.go:199]: Done

File: pkg/cmd/util_containerization.go (hunk 16 above)
Comment (KuthumiPepple) [reply pkg/cmd/util_containerization.go:102]: done

File: pkg/cmd/util_containerization.go (hunk 19 above)
Comment (KuthumiPepple) [reply pkg/cmd/util_containerization.go]: done

File: pkg/cmd/util_dependencies.go (hunk 20 above)
Comment (KuthumiPepple) [reply pkg/cmd/util_dependencies.go]: done

File: pkg/cmd/version.go (hunk 22 above)
Comment (KuthumiPepple) [reply pkg/cmd/version.go]: done

File: pkg/cmd/delete.go [hunk 27]
```diff
@@ -139,14 +139,14 @@ func getIntegration(ctx context.Context, c client.Client, name string, namespace
 	return &answer, nil
 }
 
-func deleteIntegration(ctx context.Context, c client.Client, integration *v1.Integration) error {
+func deleteIntegration(cmd *cobra.Command, ctx context.Context, c client.Client, integration *v1.Integration) error {
```
[the remark this answers is not in the document]
Comment (KuthumiPepple) [reply pkg/cmd/delete.go]: done

File: pkg/cmd/delete.go (hunk 23 above)
Comment (KuthumiPepple) [reply pkg/cmd/delete.go]: fixed

File: pkg/cmd/util_dependencies.go (hunk 26 above)
Comment (KuthumiPepple) [reply pkg/cmd/util_dependencies.go]: fixed

File: pkg/cmd/debug.go [hunk 28]
```diff
@@ -100,15 +100,15 @@ func (o *debugCmdOptions) run(cmd *cobra.Command, args []string) error {
 			// Context canceled
 			return
 		}
-		fmt.Printf("Disabling debug mode on integration %q\n", name)
+		fmt.Fprintf(cmd.OutOrStdout(), "Disabling debug mode on integration %q\n", name)
```
Comment (astefanutti) [inline pkg/cmd/debug.go:103]: `Fprintln` can be used here also.

File: pkg/cmd/describe_kamelet.go [hunk 29]
```diff
@@ -82,12 +82,12 @@ func (command *describeKameletCommandOptions) run(cmd *cobra.Command, args []str
...
 		if desc, err := command.describeKamelet(cmd, kamelet); err == nil {
-			fmt.Print(desc)
+			fmt.Fprint(cmd.OutOrStdout(), desc)
 		} else {
-			fmt.Println(err)
+			fmt.Fprintln(cmd.ErrOrStderr(), err)
 		}
 	} else {
-		fmt.Printf("Kamelet '%s' does not exist.\n", args[0])
+		fmt.Fprintf(cmd.OutOrStdout(), "Kamelet '%s' does not exist.\n", args[0])
```
Comment (astefanutti) [inline pkg/cmd/describe_kamelet.go:90]: `Fprintln` can be used here also.

File: pkg/cmd/describe_kit.go [hunk 30]
```diff
@@ -81,12 +81,12 @@ func (command *describeKitCommandOptions) run(cmd *cobra.Command, args []string)
...
 		if desc, err := command.describeIntegrationKit(cmd, kit); err == nil {
-			fmt.Print(desc)
+			fmt.Fprint(cmd.OutOrStdout(), desc)
 		} else {
-			fmt.Println(err)
+			fmt.Fprintln(cmd.ErrOrStderr(), err)
 		}
 	} else {
-		fmt.Printf("IntegrationKit '%s' does not exist.\n", args[0])
+		fmt.Fprintf(cmd.OutOrStdout(), "IntegrationKit '%s' does not exist.\n", args[0])
```
Comment (astefanutti) [inline pkg/cmd/describe_kit.go:89]: `Fprintln` can be used here also.

File: pkg/cmd/kamelet_delete.go [hunk 31]
```diff
@@ -139,6 +139,6 @@ func (command *kameletDeleteCommandOptions) delete(name string) error {
 		}
 		return fmt.Errorf("error deleting kamelet \"%s\": %w", name, err)
 	}
-	fmt.Printf("kamelet \"%s\" has been deleted\n", name)
+	fmt.Fprintf(cmd.OutOrStdout(), "kamelet \"%s\" has been deleted\n", name)
```
Comment (astefanutti) [inline pkg/cmd/kamelet_delete.go:142]: `Fprintln` can be used here also.

File: pkg/cmd/kit_create.go [hunk 32]
```diff
@@ -175,22 +175,22 @@ func (command *kitCreateCommandOptions) run(_ *cobra.Command, args []string) err
...
 
 	if err != nil {
-		fmt.Print(err.Error())
+		fmt.Fprint(cmd.ErrOrStderr(), err.Error())
 		return nil
 	}
 
 	if !existed {
-		fmt.Printf("integration kit \"%s\" created\n", kit.Name)
+		fmt.Fprintf(cmd.OutOrStdout(), "integration kit \"%s\" created\n", kit.Name)
```
Comment (astefanutti) [inline pkg/cmd/kit_create.go:191]: `Fprintln` can be used here also.

File: pkg/cmd/kit_create.go [hunk 33]
```diff
@@ -175,22 +175,22 @@ func (command *kitCreateCommandOptions) run(_ *cobra.Command, args []string) err
...
 	} else {
-		fmt.Printf("integration kit \"%s\" updated\n", kit.Name)
+		fmt.Fprintf(cmd.OutOrStdout(), "integration kit \"%s\" updated\n", kit.Name)
```
Comment (astefanutti) [inline pkg/cmd/kit_create.go:193]: `Fprintln` can be used here also.

File: pkg/cmd/kit_delete.go [hunk 34]
```diff
@@ -144,7 +144,7 @@ func (command *kitDeleteCommandOptions) delete(name string) error {
 		return fmt.Errorf("no integration kit found with name \"%s\"", kit.Name)
 	}
 
-	fmt.Printf("integration kit \"%s\" has been deleted\n", kit.Name)
+	fmt.Fprintf(cmd.OutOrStdout(), "integration kit \"%s\" has been deleted\n", kit.Name)
```
Comment (astefanutti) [inline pkg/cmd/kit_delete.go:147]: `Fprintln` can be used here also.

File: pkg/cmd/log.go [hunk 35]
```diff
@@ -128,8 +128,8 @@ func (o *logCmdOptions) run(cmd *cobra.Command, args []string) error {
 			//
 			// Found the running integration so step over to scraping its pod log
 			//
-			fmt.Printf("Integration '%s' is now running. Showing log ...\n", integrationID)
-			if err := k8slog.Print(o.Context, c, &integration, cmd.OutOrStdout()); err != nil {
+			fmt.Fprintf(cmd.OutOrStdout(), "Integration '%s' is now running. Showing log ...\n", integrationID)
```
Comment (astefanutti) [inline pkg/cmd/log.go:131]: `Fprintln` can be used here also.

File: pkg/cmd/modeline.go [hunk 36]
```diff
@@ -71,7 +71,7 @@ func NewKamelWithModelineCommand(ctx context.Context, osArgs []string) (*cobra.C
 	originalFlags := osArgs[1:]
 	rootCmd, flags, err := createKamelWithModelineCommand(ctx, originalFlags)
 	if err != nil {
-		fmt.Printf("Error: %s\n", err.Error())
+		fmt.Fprintf(rootCmd.ErrOrStderr(), "Error: %s\n", err.Error())
```
Comment (astefanutti) [inline pkg/cmd/modeline.go:74]: `Fprintln` can be used here also.

File: pkg/cmd/uninstall.go [hunk 37]
```diff
@@ -209,71 +209,71 @@ func (o *uninstallCmdOptions) uninstallClusterWideResources(ctx context.Context,
...
 		}
-		fmt.Printf("Camel K Service Accounts removed from namespace %s\n", o.Namespace)
+		fmt.Fprintln(cmd.OutOrStdout(), "Camel K Service Accounts removed from namespace", o.Namespace)
 	}
 
 	return nil
 }
 
-func (o *uninstallCmdOptions) uninstallNamespaceResources(ctx context.Context, c client.Client) error {
+func (o *uninstallCmdOptions) uninstallNamespaceResources(cmd *cobra.Command, ctx context.Context, c client.Client) error {
```
Comment (astefanutti) [inline pkg/cmd/uninstall.go:257]: The `ctx` argument should be declared in first position.

File: pkg/cmd/rebuild.go [hunk 38]
```diff
@@ -69,7 +69,7 @@ func (o *rebuildCmdOptions) rebuild(_ *cobra.Command, args []string) error {
 		return err
 	}
 
-	fmt.Printf("%d integrations have been rebuilt\n", len(integrations))
+	fmt.Fprintf(cmd.OutOrStdout(), "%d integrations have been rebuilt\n", len(integrations))
```
Comment (astefanutti) [inline pkg/cmd/rebuild.go:72]: `Fprintln` can be used here also.

File: pkg/cmd/run.go [hunk 39]
```diff
@@ -287,10 +287,10 @@ func (o *runCmdOptions) run(cmd *cobra.Command, args []string) error {
 				// Context canceled
 				return
 			}
-			fmt.Printf("Run integration terminating\n")
+			fmt.Fprintf(cmd.OutOrStdout(), "Run integration terminating\n")
```
Comment (astefanutti) [inline pkg/cmd/run.go:290]: `Fprintln` can be used here also.

**Review by astefanutti — COMMENTED** [review]
Thanks. There are a couple of leftovers for ``Fprintln`. It'll be good to go after that 👍🏼.

File: pkg/cmd/debug.go (hunk 28 above)
Comment (KuthumiPepple) [reply pkg/cmd/debug.go:103]: I did miss some of those Fprintf statements. I'll try to get them all this time. If I may ask, given the purpose of my next commit, would it not be better if do a commit amend and force push rather than do a new commit?

Comment (astefanutti) [reply pkg/cmd/debug.go:103]: No worries. I agree, amending and force push is a good idea.

**Comment by KuthumiPepple** [comment]
@astefanutti I have implemented the changes and fixed the lint errors. I also added a fix to a small error I noticed [here](https://github.com/apache/camel-k/blob/main/pkg/cmd/version.go#L176-L184). The print statements should use `aVersion` and `bVersion` not `a` and `b`. Anyway, kindly review and let me know if there are more things I need to do.

**Review by astefanutti — APPROVED** [review]
Thanks!

**Comment by KuthumiPepple** [comment]
@astefanutti I have undone a change I made by accident please try running just the openshift-build check.

**Review by astefanutti — APPROVED** [review]
