### PR TITLE
Fix #3257: work with relative paths on windows to avoid extra semicolon

### LINKED ISSUE #3257: Path-problem with local dependency (jar) on windows
Hello,

we have problems using a local dependency, running "kamel run" on Windows (Camel K 1,9,0).

```
Added mvn:de.org.legacy:legacy:jar:1.0.0 to the Integration's dependency list
spectrum - 2022/05/06 09:15:32 Pulling base image  (insecure=true)...
spectrum - 2022/05/06 09:15:32 Composing layers...
spectrum - 2022/05/06 09:15:32 Pushing image localhost:5000/maven_de_org_legacy_legacy_1_0_0_legacy-1_0_0_jar:1.0.0 (insecure=true)...
spectrum - 2022/05/06 09:15:34 existing blob: sha256:b611d19c07e6ee68e2cf32ef13168c78ffabd66b64465cbff8c50cade0ac6aa0
spectrum - 2022/05/06 09:15:34 existing blob: sha256:d2207430ab734fbbdc7a6f7437b98de7b39bf0d491a761b35d8b2634c67a0724
spectrum - 2022/05/06 09:15:34 localhost:5000/maven_de_org_legacy_legacy_1_0_0_legacy-1_0_0_jar:1.0.0: digest: sha256:e4d480c915d9f11e2bfe2b00c41a94729115afa0124006a2552d2fcf559d6367 size: 426
Uploaded: ./src/main/resources/legacy.jar to localhost:5000/maven_de_org_legacy_legacy_1_0_0_legacy-1_0_0_jar:1.0.0
spectrum - 2022/05/06 09:15:34 Pulling base image  (insecure=true)...
spectrum - 2022/05/06 09:15:34 Composing layers...
Error: Error trying to upload file://./src/main/resources/legacy.jar to the Image Registry.: wrong dir format for C:\Users\USER\AppData\Local\Temp\camel-k766362677\maven_legacy.jar_md5:. (expected "local:remote")
```

As you can see there is a problem with the windows-path. I think that the colon after the drive letter is interpreted as a delimiter.

Best Regards,
Danny

### PR DESCRIPTION
**Pull request by johnpoth**
Fixes #3257 until https://github.com/container-tools/spectrum/issues/8 is resolved. Thanks !

**Release Note**
```release-note
NONE
```

### CODE REVIEW

File: pkg/cmd/run.go [hunk 1]
```diff
@@ -972,6 +982,22 @@ func (o *runCmdOptions) uploadAsMavenArtifact(dependency maven.Dependency, path
 	return uploadChecksumFiles(path, options, platform, artifactHTTPPath, dependency)
 }
 
+func getRelativeToWorkingDirectory(path string) (string, error) {
```
Comment (squakez) [inline pkg/cmd/run.go:985]: Let's deprecate this, so we make sure to remove as soon as the root cause is fixed.

Comment (johnpoth) [reply pkg/cmd/run.go:986]: Thanks for reviewing @squakez ! Updated, thanks !

**Review by squakez — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by tadayosi** [comment]
@johnpoth FYI, the spectrum fix will be available soon #3675
