### PR TITLE
fix(trait): camel to use a single properties file 

### LINKED ISSUE #3458: Declaring multiple traits in KameletBinding fails badly
If you try something like:

```
apiVersion: [camel.apache.org/v1alpha1](https://camel.apache.org/v1alpha1)
kind: KameletBinding
metadata:
  name: test
spec:
  integration:
    traits:
      camel:
        configuration:
          properties:
           - "camel.aws.vault.accessKey=access"
           - "camel.aws.vault.secretKey=secret"
           - "camel.aws.vault.region=region"
      builder:
        configuration:
          properties:
           - "quarkus.camel.service.discovery.include-patterns=META-INF/services/org/apache/camel/properties-function/*"
  source:
    ref:
      kind: Kamelet
      apiVersion: [camel.apache.org/v1alpha1](https://camel.apache.org/v1alpha1)
      name: timer-source
    properties:
      period: "5000"
      message: '"Invocation"'
  steps:
  - ref:
      kind: Kamelet
      apiVersion: [camel.apache.org/v1alpha1](https://camel.apache.org/v1alpha1)
      name: http-sink
    properties:
      url: "https://finnhub.io/api/v1/quote?symbol=AAPL&token={{aws:finnhub-token}}"
  sink:
    ref:
      kind: Kamelet
      apiVersion: [camel.apache.org/v1alpha1](https://camel.apache.org/v1alpha1)
      name: log-sink
```

This will fail with:

`{"level":"error","ts":1658164253.419387,"logger":"controller.integration-controller","msg":"Reconciler error","reconciler group":"camel.apache.org","reconciler kind":"Integration","name":"test","namespace":"default","error":"error executing post actions: error during apply resource: default/test: failed to create typed patch object (default/test; apps/v1, Kind=Deployment): errors:\n  .spec.template.spec.containers[name=\"integration\"].volumeMounts: duplicate entries for key [mountPath=\"/etc/camel/conf.d/user.properties\"]\n  .spec.template.spec.volumes: duplicate entries for key [name=\"user-properties\"]","errorVerbose":"error during apply resource: default/test: failed to create typed patch object (default/test; apps/v1, Kind=Deployment): errors:\n  .spec.template.spec.containers[name=\"integration\"].volumeMounts: duplicate entries for key [mountPath=\"/etc/camel/conf.d/user.properties\"]\n  .spec.template.spec.volumes: duplicate entries for key [name=\"user-properties\"]\nerror executing post actions\ngithub.com/apache/camel-k/pkg/trait.Apply\n\tgithub.com/apache/camel-k/pkg/trait/trait.go:55\ngithub.com/apache/camel-k/pkg/controller/integration.(*monitorAction).Handle\n\tgithub.com/apache/camel-k/pkg/controller/integration/monitor.go:118\ngithub.com/apache/camel-k/pkg/controller/integration.(*reconcileIntegration).Reconcile\n\tgithub.com/apache/camel-k/pkg/controller/integration/integration_controller.go:309\ngithub.com/apache/camel-k/pkg/util/monitoring.(*instrumentedReconciler).Reconcile\n\tgithub.com/apache/camel-k/pkg/util/monitoring/controller.go:70\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227\nruntime.goexit\n\truntime/asm_amd64.s:1371","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.10.3/pkg/internal/controller/controller.go:227"}
`

I don't know if the declaration is wrong, but I prefer open an issue to track.

### PR DESCRIPTION
**Pull request by squakez**
Removed duplicated properties file created by the trait and merged into a single one.

Closes #3458

**Release Note**
```release-note
fix(trait): camel to use a single properties file
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

File: e2e/global/common/kamelet_binding_test.go [hunk 1]
```diff
@@ -143,3 +172,29 @@ func createErrorProducerKamelet(ns string, name string) func() error {
 
 	return CreateKamelet(ns, name, flow, props, nil)
 }
+
+func createTimerKamelet(ns string, name string) func() error {
```
Comment (tadayosi) [inline e2e/global/common/kamelet_binding_test.go:176]: There is already `CreateTimerKamelet` in test_support.go. Should we still deplicate the func here?

**Review by tadayosi — COMMENTED** [review]
One comment but all others look good to me.
