### PR TITLE
fix: camel-k ignores changes to traits configured using annotations 

### LINKED ISSUE #3479: camel-k ignores changes to traits configured using annotations
Assuming that you have a binding like the one below were annotations are used to configure traits:

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: timer2log
  annotations:
    trait.camel.apache.org/container.image: acme/bad:1
    trait.camel.apache.org/jvm.enabled: "false"
    trait.camel.apache.org/kamelets.enabled: "false"
spec:
  integration:
    configuration:
      - type: configmap
        value: timer2log-config
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: timer-source
    properties:
      message: "foo"
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: log-sink
```      

In this specific case as example, the container image that must be used to run the Integration is set set using the  `trait.camel.apache.org/container.image: acme/bad:1` annotation. 
If you update the resource and you change only the container image, then the reconcile loop is not triggered because the kamelet binding controller [take into account only the phase or the generation ](https://github.com/apache/camel-k/blob/b004a5a250fa0a816acd6a57c0378c17c6935b58/pkg/controller/kameletbinding/kamelet_binding_controller.go#L93-L94)(which does not change when only the matadata is amended ).

Since annotation can be used to configure traits,, they should be taken into account.

### PR DESCRIPTION
**Pull request by lburgazzoli**
**Release Note**
```release-note
NONE
```
Fixes #3479

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@squakez @tadayosi @christophd can you ahve a look ? btw I'm not sure if that's the proper way to solve the issue but

File: pkg/controller/integration/integration_controller.go [hunk 1]
```diff
@@ -75,6 +77,109 @@ func newReconciler(mgr manager.Manager, c client.Client) reconcile.Reconciler {
 	)
 }
 
+func integrationUpdateFunc(old *v1.Integration, it *v1.Integration) bool {
```
Comment (squakez) [inline pkg/controller/integration/integration_controller.go:80]: +1 for encapsulating these functions. However, I could not understand if there is any logic change in them or it was just the encapsulation which changed. Can you clarify?

File: pkg/controller/integration/kits.go [hunk 2]
```diff
@@ -82,6 +82,18 @@ func lookupKitsForIntegration(ctx context.Context, c ctrl.Reader, integration *v
...
+// sameOrMatch returns whether the v1.IntegrationKit ios the one used by the v1.Integration or if it meets the
+// requirements of the v1.Integration.
+func sameOrMatch(kit *v1.IntegrationKit, integration *v1.Integration) (bool, error) {
+	if integration.Status.IntegrationKit != nil {
+		if integration.Status.IntegrationKit.Namespace == kit.Namespace && integration.Status.IntegrationKit.Name == kit.Name {
+			return true, nil
+		}
+	}
+
+	return integrationMatches(integration, kit)
```
Comment (squakez) [inline pkg/controller/integration/kits.go:94]: I've just fixed another possibly related issue here #3487. In that case it was failing because the `match` always returned false when an IntegrationKit was on error. Not sure if there is any check in the `integrationMatches` that is influencing the failure here, and if it makes sense to revisit it. I'd expect the `integrationMatches` to take care of those new added conditions as well.

**Review by squakez — APPROVED** [review]
Good for me. Just a couple of comments though.

File: pkg/controller/integration/integration_controller.go (hunk 1 above)
Comment (lburgazzoli) [reply pkg/controller/integration/integration_controller.go:80]: the linter was complaining about complexity of the method so I created dedicated functions to make the method more readable.

File: pkg/controller/integration/kits.go (hunk 2 above)
Comment (lburgazzoli) [reply pkg/controller/integration/kits.go:94]: For what I understood, in the case the status of a kit should not influence the trigger as in fact every change to a kit should result in a reconcile being triggered. Then the integration controller should decide what to do so I guess your changes are improving also this case.

File: pkg/trait/util.go [hunk 3]
```diff
@@ -320,3 +321,26 @@ func getBuilderTask(tasks []v1.Task) *v1.BuilderTask {
...
+func Equals(oldObject metav1.Object, newObject metav1.Object) bool {
+	if len(oldObject.GetAnnotations()) != len(newObject.GetAnnotations()) {
+		return false
+	}
+
+	oldTraits := make(map[string]string)
+	newTraits := make(map[string]string)
+
+	for k, v := range oldObject.GetAnnotations() {
+		if strings.HasPrefix(k, "trait.camel.apache.org/") {
```
Comment (tadayosi) [inline pkg/trait/util.go:335]: we can use `camelv1.TraitAnnotationPrefix` here.

File: pkg/trait/util.go [hunk 4]
```diff
@@ -320,3 +321,26 @@ func getBuilderTask(tasks []v1.Task) *v1.BuilderTask {
...
+			oldTraits[k] = v
+		}
+	}
+	for k, v := range newObject.GetAnnotations() {
+		if strings.HasPrefix(k, "trait.camel.apache.org/") {
```
Comment (tadayosi) [inline pkg/trait/util.go:340]: we can use `camelv1.TraitAnnotationPrefix` here.

File: pkg/trait/util.go [hunk 5]
```diff
@@ -320,3 +321,26 @@ func getBuilderTask(tasks []v1.Task) *v1.BuilderTask {
 	}
 	return nil
 }
+
+// Equals return if traits set using annotations have changed.
+func Equals(oldObject metav1.Object, newObject metav1.Object) bool {
```
Comment (tadayosi) [inline pkg/trait/util.go:326]: I first saw the function name and misunderstood it as comparing both annotations and spec.traits. It's only when I stared at the arg types that I understood the correct intent.

Apart from the function name, is it not needed to actually compare the traits under specs as well for where the func is invoked?  Are changes to traits under spec handled in a different mechanics?

File: pkg/controller/integration/kits.go [hunk 6]
```diff
@@ -82,6 +82,18 @@ func lookupKitsForIntegration(ctx context.Context, c ctrl.Reader, integration *v
 	return kits, nil
 }
 
+// sameOrMatch returns whether the v1.IntegrationKit ios the one used by the v1.Integration or if it meets the
+// requirements of the v1.Integration.
+func sameOrMatch(kit *v1.IntegrationKit, integration *v1.Integration) (bool, error) {
```
Comment (tadayosi) [inline pkg/controller/integration/kits.go:87]: I think this func is a necessary one to have, but also wonder if `integrationMatches()` should be aware of the traits in annotations as well. Currently `integrationMatches()` only compares `it.spec.traits` with `kit.spec.traits` but shouldn't it really compare the combination of annotations and spec.traits?

**Review by tadayosi — COMMENTED** [review]
Apart from my comments, there's one silently failing e2e test in `common-it`. I'd like to check if it's really not related to this pull req or not.
```
2022-07-25T15:08:07.0934307Z === RUN   TestKameletBindingScale
...
2022-07-25T15:10:44.4605241Z     scale_binding_test.go:58: 
2022-07-25T15:10:44.4605677Z         Timed out after 60.003s.
2022-07-25T15:10:44.4606001Z         Expected
2022-07-25T15:10:44.4606444Z             <v1.ConditionStatus>: False
2022-07-25T15:10:44.4606760Z         to equal
2022-07-25T15:10:44.4607175Z             <v1.ConditionStatus>: True
```
See #3465 for the issue of e2e silently failing. It's already fixed in the main branch.

File: pkg/trait/util.go (hunk 5 above)
Comment (lburgazzoli) [reply pkg/trait/util.go:326]: Yes I think the current solution is suboptimal but with my outdated knowledge of the codebase I tried to be conservative.

I think the proper solution would be to always reason on a synthetic view of the trait as in fact we may have cases where two resources have the same traits but defined in a different way.

I'll try to work on something

File: pkg/controller/integration/kits.go (hunk 6 above)
Comment (lburgazzoli) [reply pkg/controller/integration/kits.go:87]: agree, see the other comments

File: pkg/trait/util.go (hunk 5 above)
Comment (lburgazzoli) [reply pkg/trait/util.go]: pushed a  new version of the PR with better support for traits

**Review by tadayosi — APPROVED** [review]
Great refactoring!

**Review by valdar — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@tadayosi @christophd I see knative test failing but I'm unsure if they are related to this change or not. I may need some help to troubleshoot the failure

**Comment by tadayosi** [comment]
@lburgazzoli We've done a lot of efforts to stabilise the e2e tests and now they are reilable enough to keep all green before merging a pull req. The fact that `knative/yaks` fails 3 times out of 3 suggests it's likely some changes in this fix have caused it.

I'm not knowledgeable about the yaks test either but I'd start from replicating the automated test manually and see what's causing this error:
> error: timed out waiting for the condition on kameletbindings/timer-source-binding-display

File: pkg/trait/util.go [hunk 7]
```diff
@@ -29,17 +29,36 @@ import (
...
 	v1 "github.com/apache/camel-k/pkg/apis/camel/v1"
+	"github.com/apache/camel-k/pkg/apis/camel/v1alpha1"
 	"github.com/apache/camel-k/pkg/client"
 	"github.com/apache/camel-k/pkg/metadata"
 	"github.com/apache/camel-k/pkg/util"
 	"github.com/apache/camel-k/pkg/util/camel"
 	"github.com/apache/camel-k/pkg/util/property"
 )
 
+type Unstructured map[string]map[string]interface{}
```
Comment (astefanutti) [inline pkg/trait/util.go:44]: I'd suggest not to used `Unstructured` to avoid confusion with the eponymous type from k8s, maybe `Traits` or `TraitOptions`.

File: pkg/controller/kameletbinding/monitor.go [hunk 8]
```diff
@@ -76,14 +77,25 @@ func (action *monitorAction) Handle(ctx context.Context, kameletbinding *v1alpha
...
-	if !equality.Semantic.DeepDerivative(expected.Spec, it.Spec) || operatorIDChanged {
-		action.L.Info("Monitor: KameletBinding needs a rebuild")
+	semanticEquality := equality.Semantic.DeepDerivative(expected.Spec, it.Spec)
+
+	if !semanticEquality || operatorIDChanged || !sameTraits {
+		action.L.Info(
+			"Monitor: KameletBinding needs a rebuild",
+			"semantic-equality", !semanticEquality,
+			"operatorid-changed", operatorIDChanged,
+			"traites-changed", !sameTraits)
```
Comment (astefanutti) [inline pkg/controller/kameletbinding/monitor.go:98]: `traites-changed` -> `traits-changed`

File: pkg/controller/kameletbinding/monitor.go [hunk 9]
```diff
@@ -76,14 +77,25 @@ func (action *monitorAction) Handle(ctx context.Context, kameletbinding *v1alpha
...
 		return nil, err
 	}
 
-	if !equality.Semantic.DeepDerivative(expected.Spec, it.Spec) || operatorIDChanged {
-		action.L.Info("Monitor: KameletBinding needs a rebuild")
+	semanticEquality := equality.Semantic.DeepDerivative(expected.Spec, it.Spec)
+
+	if !semanticEquality || operatorIDChanged || !sameTraits {
+		action.L.Info(
+			"Monitor: KameletBinding needs a rebuild",
```
Comment (astefanutti) [inline pkg/controller/kameletbinding/monitor.go:95]: `Monitor: KameletBinding needs a rebuild` -> `KameletBinding needs a rebuild`

File: pkg/controller/integration/integration_controller.go [hunk 10]
```diff
@@ -75,6 +77,115 @@ func newReconciler(mgr manager.Manager, c client.Client) reconcile.Reconciler {
...
+		opts = append(opts, ctrl.InNamespace(kit.Namespace))
+	}
+	if err := c.List(context.Background(), list, opts...); err != nil {
+		log.Error(err, "Failed to retrieve integration list")
+		return requests
+	}
+
+	for i := range list.Items {
+		integration := &list.Items[i]
+		log.Debug("Integration Controller: Assessing integration", "integration", integration.Name, "namespace", integration.Namespace)
```
Comment (astefanutti) [inline pkg/controller/integration/integration_controller.go:130]: Probably not introduced by this PR, but seems better to re-used the scoped logger, e.g. `Log.Debug("Filtering integration from kit changes", ...)`.

File: pkg/controller/integration/integration_controller.go [hunk 11]
```diff
@@ -75,6 +77,115 @@ func newReconciler(mgr manager.Manager, c client.Client) reconcile.Reconciler {
...
+
+		match, err := sameOrMatch(kit, integration)
+		if err != nil {
+			log.Errorf(err, "Error matching integration %q with kit %q", integration.Name, kit.Name)
```
Comment (astefanutti) [inline pkg/controller/integration/integration_controller.go:134]: Maybe use `Log.ForIntegration(it).Error(...` for consistency.

**Review by astefanutti — APPROVED** [review]
Few comments, otherwise LGTM 👍🏼.

File: pkg/trait/util.go (hunk 7 above)
Comment (lburgazzoli) [reply pkg/trait/util.go:44]: what about just Options ? just because GoLand keep telling me that Trait is implicit by the package name :)

Comment (astefanutti) [reply pkg/trait/util.go:44]: Right, `Options` came also to my mind, so that sounds perfect to me :)

**Comment by lburgazzoli** [comment]
> Few comments, otherwise LGTM 👍🏼.

Suggestions have been implemented, I guess the overall logging stuff may need to be improved

**Comment by lburgazzoli** [comment]
@christophd I may need some help trying to understand what the failure is about
    
    kamelet-binding-http (kamelet-binding-http): Failure caused by InitializationError - Failed to run installation: exit status 1

File: pkg/trait/util.go [hunk 12]
```diff
@@ -388,34 +388,43 @@ func KameletBindingsHaveSameTraits(i1 *v1alpha1.KameletBinding, i2 *v1alpha1.Kam
 }
 
 // IntegrationAndBindingSameTraits return if traits are the same.
+// The comparison happen for a subset of traits as during the trait processing, some traits may be
```
Comment (astefanutti) [inline pkg/trait/util.go:391]: nit: happen -> happens or "is done for the subset of traits defines on the binding"

**Review by astefanutti — APPROVED** [review]
