### PR TITLE
Extra repositories

### LINKED ISSUE #2327: maven-repository flag is not honored in the run command
for example the following fails:

`./kamel run --name  extra-repo examples/languages/Sample.java --dependency mvn:jakarta.annotation:jakarta.annotation-api:1.3.5.redhat-00002 --maven-repository https://maven.repository.redhat.com/ga@id=redhat`

### PR DESCRIPTION
**Pull request by johnpoth**
Fixes #2327, thanks !

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by nicolaferraro — APPROVED** [review]

**Comment by nicolaferraro** [comment]
Thanks, can you check the conflict?

**Comment by johnpoth** [comment]
Done ! Thanks

File: pkg/apis/camel/v1/common_types.go [hunk 1]
```diff
@@ -93,8 +93,9 @@ type MavenSpec struct {
 	// A JKS formatted keystore is automatically created to store the CA certificate(s),
 	// and configured to be used as a trusted certificate(s) by the Maven commands.
 	// Note that the root CA certificates are also imported into the created keystore.
-	CASecret *corev1.SecretKeySelector `json:"caSecret,omitempty"`
-	Timeout  *metav1.Duration          `json:"timeout,omitempty"`
+	CASecret     *corev1.SecretKeySelector `json:"caSecret,omitempty"`
+	Timeout      *metav1.Duration          `json:"timeout,omitempty"`
+	Repositories []string                  `json:"repositories,omitempty"`
```
Comment (astefanutti) [inline pkg/apis/camel/v1/common_types.go:98]: Would it be possible to use the _structured_ repository definition in the API? The string representation is rather a CLI convenience, and it might be better avoiding leaking it into the API.

Comment (johnpoth) [reply pkg/apis/camel/v1/common_types.go:98]: Ah it's already defined that way in the [IntegrationKitSpec](https://github.com/apache/camel-k/blob/main/pkg/apis/camel/v1/integrationkit_types.go#L35), is that okay ?

Comment (astefanutti) [reply pkg/apis/camel/v1/common_types.go:98]: Ah yes, I think we can deal with the `IntegrationKitSpec` refactoring in #2321. For the `Build` API, we have the opportunity to avoid repeating the mistake of using a serialised string representation for a complex structure.

Comment (johnpoth) [reply pkg/apis/camel/v1/common_types.go:98]: Makes sense, looks like using the [Repostory](https://github.com/apache/camel-k/blob/main/pkg/util/maven/maven_types.go#L29) creates an import cycle due to Maven Log depending on camel v1, will look into it...

Comment (astefanutti) [reply pkg/apis/camel/v1/common_types.go:98]: Yes, the existing `Repository` struct is in a util package, solely used for XML serialisation. It can either be moved to the API module, or we can introduce a similar struct in the API module.

Comment (johnpoth) [reply pkg/apis/camel/v1/common_types.go]: Done, I've moved the Repository bits into the API. The alternative would to duplicate them and have a helper method to map from one Repository structure to the other. Thanks !

**Review by astefanutti — APPROVED** [review]
LGTM!

File: pkg/apis/camel/v1/common_types.go (hunk 1 above)
Comment (astefanutti) [reply pkg/apis/camel/v1/common_types.go]: Thanks, and sorry for the extra conflicts 😅.

**Comment by astefanutti** [comment]
Thanks!
