### PR TITLE
The example RestWithRestlet does not work calling its service via curl or webbrowser

### LINKED ISSUE #402: The example RestWithRestlet does not work calling its service via curl or webbrowser
For example with a local minishift I get an error response from kubernets

curl http://rest-with-restlet-mykamel2.192.168.64.8.nip.io/hello

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #402

### CODE REVIEW

File: pkg/trait/service.go [hunk 1]
```diff
@@ -79,7 +79,7 @@ func (t *serviceTrait) Apply(e *Environment) (err error) {
 	}
 	port := corev1.ServicePort{
 		Name:       httpPortName,
-		Port:       80,
+		Port:       int32(t.Port),
```
Comment (lburgazzoli) [inline pkg/trait/service.go]: @astefanutti I had to change as otherwise  the port is set on the trait is not taken into account but I do not know the reason of the change, can you please validate ?

Comment (astefanutti) [reply pkg/trait/service.go]: @lburgazzoli I think that it should work without this change. I think the original issue is due to the host bound to `localhost`. I've tested the sample with service port 80 and it works on my local setup (Minishift). Some Linux capabilities exist for port binding on pods but I do not know of any restrictions applicable to services.

Comment (lburgazzoli) [reply pkg/trait/service.go]: reverted
