### PR TITLE
Fix doc port name

### LINKED ISSUE #2761: Default value of trait container.port-name is missing from catalog
previously there was `http`. it is still mentioned as the default one in description but missing from the catalog json

```
			{
				"name": "port-name",
				"type": "string",
				"description": "To configure a different port name for the port exposed by the container (default `http`)."
			}
```

can be retrieved using `kamel help trait container -o json`

tried using kamel 1.7.0

### PR DESCRIPTION
**Pull request by oscerd**
Fixes #2761 

**Release Note**
```release-note
NONE
```

### CODE REVIEW

File: pkg/trait/container.go [hunk 1]
```diff
@@ -68,7 +68,7 @@ type containerTrait struct {
 	Expose *bool `property:"expose" json:"expose,omitempty"`
 	// To configure a different port exposed by the container (default `8080`).
 	Port int `property:"port" json:"port,omitempty"`
-	// To configure a different port name for the port exposed by the container (default `http`).
+	// To configure a different port name for the port exposed by the container. it defaults to `http` only when the `expose` parameter is true.
```
Comment (squakez) [inline pkg/trait/container.go:71]: Maybe uppercase here. "It defaults ..."

**Review by squakez — APPROVED** [review]

**Review by astefanutti — APPROVED** [review]

File: pkg/trait/container.go (hunk 1 above)
Comment (oscerd) [reply pkg/trait/container.go]: should be fine now.
