### PR TITLE
fix(controller): camelcatalog default timeout

### LINKED ISSUE #4226: CamelCatalog reconciliation fail
@mertdotcc is having some problem in E2E test due to the fact that for some reason, the CamelCatalog does not end the reconciliation. It seems that the builder image layers are pushed, but it miss the last step:
```
{"level":"info","ts":1680601767.6983678,"logger":"camel-k.controller.catalog","msg":"spectrum - 2023/04/04 09:49:27 Pushing image 10.104.97.216/camel-k-runtime-quarkus-builder:3.20.1-snapshot (insecure=true)..."}
{"level":"info","ts":1680601767.712454,"logger":"camel-k.controller.catalog","msg":"spectrum - 2023/04/04 09:49:27 existing blob:
...
{"level":"info","ts":1680601767.719584,"logger":"camel-k.controller.catalog","msg":"spectrum - 2023/04/04 09:49:27 existing blob: sha256:e20685d69d54b04bb51f52d5a4a0e35b77fc1d700c9f0a3c9dafffa6a5eca6e1"}
{"level":"info","ts":1680601767.7247279,"logger":"camel-k.controller.catalog","msg":"spectrum - 2023/04/04 09:49:27 existing blob: sha256:9eb5f0bec9aa2593bb3ed25b455d5b34ec9bcfa4e4e2f3310bd2ecb8515c71e1"}
{"level":"info","ts":1680601767.7247653,"logger":"camel-k.controller.catalog","msg":"spectrum - 2023/04/04 09:49:27 existing blob: sha256:aa67c3e88889892448b19050494315ea4dbc8123adcd4909ecb7b0bbb0111095"}
{"level":"info","ts":1680601767.7258403,"logger":"camel-k.controller.catalog","msg":"spectrum - 2023/04/04 09:49:27 existing blob: sha256:9adc3f4140a41250882b5409a1d2232f1c6eba4126ee2bad6fef6a987d2c84aa"}
{"
```
It misses something like:
```
test-9a6a38e6-2210-4517-bc22-29b300ecbcae camel-k-operator-6dff9f56bb-wr2rv camel-k-operator {"level":"info","ts":1680602621.8160427,"logger":"camel-k.controller.catalog","msg":"spectrum - 2023/04/04 10:03:41 10.100.175.64/camel-k-runtime-quarkus-builder:3.20.1-snapshot: digest: sha256:57904c8dc5467c3a94228884c03bff5cebe666ea53f35fff39ab6fd667173a11 size: 3516"}
```
which would continue the reconciliation. Whatever the case, we need to provide a timeout to avoid the reconciliation to stuck on the push, and report back to the user.

### PR DESCRIPTION
**Pull request by squakez**
Closes #4226

**Release Note**
```release-note
fix(controller): camelcatalog default timeout
```

### CODE REVIEW

**Comment by squakez** [comment]
@mertdotcc, altough this is not directly fix the issue you're experiencing, it may give some useful hints on the failure. If the controller is stuck on the registry while is building, now it will timeout (by default after 60 seconds). Once this is approved and merged, you can rebase and check your local tests.

File: pkg/client/camel/applyconfiguration/camel/v1/integrationplatformbuildspec.go [hunk 1]
```diff
@@ -27,15 +27,16 @@ import (
...
-	Timeout                *metav1.Duration                            `json:"timeout,omitempty"`
-	Maven                  *MavenSpecApplyConfiguration                `json:"maven,omitempty"`
-	PublishStrategyOptions map[string]string                           `json:"PublishStrategyOptions,omitempty"`
+	BuildStrategy           *v1.BuildStrategy                           `json:"buildStrategy,omitempty"`
+	PublishStrategy         *v1.IntegrationPlatformBuildPublishStrategy `json:"publishStrategy,omitempty"`
+	RuntimeVersion          *string                                     `json:"runtimeVersion,omitempty"`
+	RuntimeProvider         *v1.RuntimeProvider                         `json:"runtimeProvider,omitempty"`
+	BaseImage               *string                                     `json:"baseImage,omitempty"`
+	Registry                *RegistrySpecApplyConfiguration             `json:"registry,omitempty"`
+	BuildCatalogToolTimeout *int                                        `json:"buildCatalogToolTimeout,omitempty"`
```
Comment (gansheer) [inline pkg/client/camel/applyconfiguration/camel/v1/integrationplatformbuildspec.go:36]: Just curious : why not use the same type as the `Timeout` parameter ?

Comment (squakez) [reply pkg/client/camel/applyconfiguration/camel/v1/integrationplatformbuildspec.go:36]: Good point. I will change accordingly.

**Review by gansheer — APPROVED** [review]
